import TrainingShell from "@/components/TrainingShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createEmptyCropWalkEvidenceDraft, cropWalkEvidenceLabRequirements, hasComparableCropWalkEvidence, type CropWalkEvidenceDraft } from "@shared/cropWalkEvidenceLab";
import { ArrowLeft, CheckCircle2, ClipboardCheck, Eye, FileDown, MapPinned, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function CropWalkEvidenceLab() {
  const [, setLocation] = useLocation();
  const [draft, setDraft] = useState<CropWalkEvidenceDraft>(createEmptyCropWalkEvidenceDraft);
  const updateObservation = (index: number, field: "location" | "cropAndSoilCondition" | "patternOrComparison", value: string) => setDraft(current => ({ ...current, observations: current.observations.map((observation, observationIndex) => observationIndex === index ? { ...observation, [field]: value } : observation) }));
  const completeEvidence = hasComparableCropWalkEvidence(draft);

  return <TrainingShell wide><main className="mx-auto max-w-[1200px] px-5 py-7 sm:px-8 lg:py-9 print:max-w-none print:px-0"><button type="button" onClick={() => setLocation("/course/crop-observation")} className="inline-flex items-center gap-1.5 text-xs font-bold text-[#59705e] hover:text-[#1f4a37]"><ArrowLeft className="h-3.5 w-3.5" />Back to Module 3</button>
    <header className="mt-5 rounded-[28px] border border-[#cfe1d0] bg-[#eef7ec] px-6 py-7 sm:px-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge className="border-0 bg-white text-[10px] font-bold uppercase tracking-[0.15em] text-[#4a7753]">Voluntary field practice</Badge><h1 className="mt-4 max-w-3xl font-serif text-4xl font-semibold tracking-[-0.055em] text-[#294a39]">Crop-Walk Evidence Lab</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#557057]">Practise a repeatable crop walk: start broad, compare field zones, record evidence before interpreting, and identify the safest next check.</p></div><MapPinned className="h-9 w-9 text-[#4d8156]" /></div><p className="mt-5 flex gap-2 rounded-xl border border-[#cae0cc] bg-white/75 p-4 text-xs leading-5 text-[#527056]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#4b8054]" />{cropWalkEvidenceLabRequirements.safetyBoundary}</p></header>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><MapPinned className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 1 · Plan the walk</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Frame a question and make the route repeatable.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Use the route to compare conditions—not to search only where a problem has already been noticed.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="crop-walk-question">Field question</Label><Textarea id="crop-walk-question" value={draft.fieldQuestion} onChange={event => setDraft(current => ({ ...current, fieldQuestion: event.target.value }))} placeholder="For example: What evidence explains uneven crop vigour across this plot?" className="mt-2 min-h-24 bg-white text-sm" /></div><div className="space-y-4"><div><Label htmlFor="crop-walk-stage">Crop stage and date context</Label><Input id="crop-walk-stage" value={draft.cropStage} onChange={event => setDraft(current => ({ ...current, cropStage: event.target.value }))} placeholder="Enter crop stage and observation date" className="mt-2 bg-white" /></div><div><Label htmlFor="crop-walk-route">Repeatable route</Label><select id="crop-walk-route" value={draft.route} onChange={event => setDraft(current => ({ ...current, route: event.target.value as CropWalkEvidenceDraft["route"] }))} className="mt-2 flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50">{cropWalkEvidenceLabRequirements.routeOptions.map(route => <option key={route}>{route}</option>)}</select></div></div></div></section>

    <section className="mt-7 rounded-[24px] border border-[#d8e6d6] bg-[#f7fbf4] p-5 sm:p-6"><div className="flex items-start gap-3"><Eye className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 2 · Compare before explaining</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Record three field zones using the same lens.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Describe what is present: crop condition, root-zone or soil context, field pattern, and the comparison. Do not name a cause yet.</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{draft.observations.map((observation, index) => <article key={observation.zone} className="rounded-xl border border-[#dce8d9] bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#648066]">Observation {index + 1}</p><h3 className="mt-2 font-serif text-xl font-semibold text-[#34513c]">{observation.zone}</h3><div className="mt-4 space-y-3"><div><Label htmlFor={`crop-walk-location-${index}`} className="text-xs">Location / map cue</Label><Input id={`crop-walk-location-${index}`} value={observation.location} onChange={event => updateObservation(index, "location", event.target.value)} placeholder="Row, zone, edge, or transect point" className="mt-1.5 bg-white text-sm" /></div><div><Label htmlFor={`crop-walk-condition-${index}`} className="text-xs">Crop and soil / water condition</Label><Textarea id={`crop-walk-condition-${index}`} value={observation.cropAndSoilCondition} onChange={event => updateObservation(index, "cropAndSoilCondition", event.target.value)} placeholder="Plant stage, vigour, leaves, roots if visible, soil surface, moisture or drainage clues" className="mt-1.5 min-h-28 bg-white text-sm" /></div><div><Label htmlFor={`crop-walk-pattern-${index}`} className="text-xs">Pattern or comparison</Label><Textarea id={`crop-walk-pattern-${index}`} value={observation.patternOrComparison} onChange={event => updateObservation(index, "patternOrComparison", event.target.value)} placeholder="What differs, where it starts, and what is similar?" className="mt-1.5 min-h-24 bg-white text-sm" /></div></div></article>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 3 · Interpret with uncertainty</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Keep more than one explanation open.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">A working explanation is a question to test, not a conclusion. Record what would strengthen, weaken, or replace it.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="crop-walk-working">Working explanation to test</Label><Textarea id="crop-walk-working" value={draft.workingExplanation} onChange={event => setDraft(current => ({ ...current, workingExplanation: event.target.value }))} placeholder="State the field pattern and a possible explanation without treating it as confirmed." className="mt-2 min-h-28 bg-white text-sm" /></div><div><Label htmlFor="crop-walk-competing">Competing explanation</Label><Textarea id="crop-walk-competing" value={draft.competingExplanation} onChange={event => setDraft(current => ({ ...current, competingExplanation: event.target.value }))} placeholder="What else could create a similar pattern?" className="mt-2 min-h-28 bg-white text-sm" /></div></div><div className="mt-4"><Label htmlFor="crop-walk-evidence">Evidence that would distinguish the explanations</Label><Textarea id="crop-walk-evidence" value={draft.evidenceToCheck} onChange={event => setDraft(current => ({ ...current, evidenceToCheck: event.target.value }))} placeholder="For example: additional comparisons, verified field records, representative sampling, current weather history, or authorised diagnostic evidence." className="mt-2 min-h-24 bg-white text-sm" /></div></section>

    <section className="mt-7 rounded-[24px] border border-[#cfe1d0] bg-[#eef7ec] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#618164]">Step 4 · Recheck or refer</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Choose the next safe evidence action.</h2></div><Button type="button" onClick={() => window.print()} variant="outline" className="rounded-full border-[#9db99d] bg-white text-xs font-bold text-[#315f47]"><FileDown className="mr-1.5 h-3.5 w-3.5" />Print field draft</Button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="crop-walk-next-step">Next step</Label><select id="crop-walk-next-step" value={draft.safeNextStep} onChange={event => setDraft(current => ({ ...current, safeNextStep: event.target.value as CropWalkEvidenceDraft["safeNextStep"] }))} className="mt-2 flex h-10 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50">{cropWalkEvidenceLabRequirements.nextStepOptions.map(step => <option key={step}>{step}</option>)}</select></div><div><Label htmlFor="crop-walk-referral">Reason to pause, recheck, or refer</Label><Textarea id="crop-walk-referral" value={draft.referralReason} onChange={event => setDraft(current => ({ ...current, referralReason: event.target.value }))} placeholder="State the uncertainty, consequence, or missing evidence that prevents a final conclusion." className="mt-2 min-h-20 bg-white text-sm" /></div></div><div className="mt-5 rounded-xl border border-[#d6e5d4] bg-white/85 p-4"><p className="flex items-center gap-2 text-sm font-bold text-[#426247]"><CheckCircle2 className="h-4 w-4 text-[#4b8054]" />Evidence-check status: {completeEvidence ? "Comparable field observations recorded" : "Complete the question, crop-stage context, and all three observation zones"}</p><p className="mt-2 text-xs leading-5 text-[#5c735f]">{cropWalkEvidenceLabRequirements.nonGatingBoundary}</p></div></section>
  </main></TrainingShell>;
}
