import TrainingShell from "@/components/TrainingShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createEmptyDripUniformityInvestigationDraft, dripUniformityInvestigationRequirements, hasCompleteDripUniformityEvidence, type DripUniformityEvidenceCheckId, type DripUniformityInvestigationDraft } from "@shared/dripUniformityInvestigation";
import { ArrowLeft, CheckCircle2, ClipboardCheck, Droplets, FileDown, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function DripUniformityInvestigationLab() {
  const [, setLocation] = useLocation();
  const [draft, setDraft] = useState(createEmptyDripUniformityInvestigationDraft);
  const ready = hasCompleteDripUniformityEvidence(draft);
  const updateCheckpoint = (index: number, field: "location" | "deliveryAndWetting" | "cropAndHardwareContext", value: string) => setDraft(current => ({ ...current, checkpoints: current.checkpoints.map((checkpoint, checkpointIndex) => checkpointIndex === index ? { ...checkpoint, [field]: value } : checkpoint) }));
  const updateCheck = (id: DripUniformityEvidenceCheckId, value: boolean) => setDraft(current => ({ ...current, evidenceChecks: { ...current.evidenceChecks, [id]: value } }));

  return <TrainingShell wide><main className="mx-auto max-w-[1200px] px-5 py-7 sm:px-8 lg:py-9 print:max-w-none print:px-0"><button type="button" onClick={() => setLocation("/course/drip-irrigation-system")} className="inline-flex items-center gap-1.5 text-xs font-bold text-[#59705e] hover:text-[#1f4a37]"><ArrowLeft className="h-3.5 w-3.5" />Back to Module 25</button>
    <header className="mt-5 rounded-[28px] border border-[#cfe1d0] bg-[#eef7ec] px-6 py-7 sm:px-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge className="border-0 bg-white text-[10px] font-bold uppercase tracking-[0.15em] text-[#4a7753]">Voluntary field practice</Badge><h1 className="mt-4 max-w-3xl font-serif text-4xl font-semibold tracking-[-0.055em] text-[#294a39]">Drip Uniformity Investigation Lab</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#557057]">Walk the system from source-near to far end, compare delivery and wetting evidence, then decide whether to recheck, clarify, or seek qualified support.</p></div><Droplets className="h-9 w-9 text-[#4d8156]" /></div><p className="mt-5 flex gap-2 rounded-xl border border-[#cae0cc] bg-white/75 p-4 text-xs leading-5 text-[#527056]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#4b8054]" />{dripUniformityInvestigationRequirements.safetyBoundary}</p></header>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><Droplets className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 1 · Frame the system question</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Start with a field comparison, not an adjustment.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Record what needs investigating and the recent operation or maintenance context before assuming that a far-end plant response proves a system fault.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="drip-lab-question">System or field question</Label><Textarea id="drip-lab-question" value={draft.systemQuestion} onChange={event => setDraft(current => ({ ...current, systemQuestion: event.target.value }))} placeholder="For example: What evidence explains different wetting or crop response across this irrigation zone?" className="mt-2 min-h-24 bg-white text-sm" /></div><div><Label htmlFor="drip-lab-context">Recent operation, source, or maintenance context</Label><Textarea id="drip-lab-context" value={draft.recentSystemContext} onChange={event => setDraft(current => ({ ...current, recentSystemContext: event.target.value }))} placeholder="Record recent operating observations, filter or source context, maintenance notes, and relevant field conditions." className="mt-2 min-h-24 bg-white text-sm" /></div></div></section>

    <section className="mt-7 rounded-[24px] border border-[#d8e6d6] bg-[#f7fbf4] p-5 sm:p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 2 · Walk source to far end</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Compare delivery, wetting, crop, and hardware clues.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Use the same observation lens at each checkpoint. Record what is observed; do not diagnose an emitter, filter, pressure, or water-quality issue from one cue.</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{draft.checkpoints.map((checkpoint, index) => <article key={checkpoint.checkpoint} className="rounded-xl border border-[#dce8d9] bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#648066]">Checkpoint {index + 1}</p><h3 className="mt-2 font-serif text-xl font-semibold text-[#34513c]">{checkpoint.checkpoint}</h3><div className="mt-4 space-y-3"><div><Label htmlFor={`drip-lab-location-${index}`} className="text-xs">Location / line cue</Label><Input id={`drip-lab-location-${index}`} value={checkpoint.location} onChange={event => updateCheckpoint(index, "location", event.target.value)} placeholder="Row, lateral, valve, inlet, or far-end cue" className="mt-1.5 bg-white text-sm" /></div><div><Label htmlFor={`drip-lab-delivery-${index}`} className="text-xs">Delivery and wetting observation</Label><Textarea id={`drip-lab-delivery-${index}`} value={checkpoint.deliveryAndWetting} onChange={event => updateCheckpoint(index, "deliveryAndWetting", event.target.value)} placeholder="Visible water delivery, wetting distribution, leaks, blockage cues, or connection condition." className="mt-1.5 min-h-28 bg-white text-sm" /></div><div><Label htmlFor={`drip-lab-crop-${index}`} className="text-xs">Crop and hardware context</Label><Textarea id={`drip-lab-crop-${index}`} value={checkpoint.cropAndHardwareContext} onChange={event => updateCheckpoint(index, "cropAndHardwareContext", event.target.value)} placeholder="Crop response, root-zone context, line condition, and comparison with other points." className="mt-1.5 min-h-24 bg-white text-sm" /></div></div></article>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 3 · Complete the investigation controls</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Verify the evidence chain before changing the system.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">The next step depends on the full source-to-far-end comparison, not one emitter or a single plant.</p></div></div><div className="mt-5 space-y-3">{dripUniformityInvestigationRequirements.evidenceChecks.map(check => <label key={check.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-[#dce8d9] bg-[#f8fbf6] p-4 transition-colors hover:bg-white"><input type="checkbox" checked={draft.evidenceChecks[check.id]} onChange={event => updateCheck(check.id, event.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-[#4b8054]" /><span className="text-sm leading-6 text-[#49614e]">{check.label}</span></label>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#cfe1d0] bg-[#eef7ec] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#618164]">Step 4 · Recheck or refer</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Choose a safe next evidence action.</h2></div><Button type="button" onClick={() => window.print()} variant="outline" className="rounded-full border-[#9db99d] bg-white text-xs font-bold text-[#315f47]"><FileDown className="mr-1.5 h-3.5 w-3.5" />Print investigation draft</Button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="drip-lab-next">Next step</Label><select id="drip-lab-next" value={draft.nextStep} onChange={event => setDraft(current => ({ ...current, nextStep: event.target.value as DripUniformityInvestigationDraft["nextStep"] }))} className="mt-2 flex h-10 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50">{dripUniformityInvestigationRequirements.nextStepOptions.map(step => <option key={step}>{step}</option>)}</select></div><div><Label htmlFor="drip-lab-pause">Reason to pause, recheck, or refer</Label><Textarea id="drip-lab-pause" value={draft.pauseOrReferral} onChange={event => setDraft(current => ({ ...current, pauseOrReferral: event.target.value }))} placeholder="Record the uncertainty, safety concern, or missing evidence that prevents a maintenance or setting decision." className="mt-2 min-h-20 bg-white text-sm" /></div></div><div className="mt-5 rounded-xl border border-[#d6e5d4] bg-white/85 p-4"><p className="flex items-center gap-2 text-sm font-bold text-[#426247]"><CheckCircle2 className="h-4 w-4 text-[#4b8054]" />Evidence-check status: {ready ? "Source-to-far-end comparison recorded" : "Complete the question, all checkpoints, and every evidence control"}</p><p className="mt-2 text-xs leading-5 text-[#5c735f]">{dripUniformityInvestigationRequirements.nonGatingBoundary}</p></div></section>
  </main></TrainingShell>;
}
