import LearnerLoading from "@/components/LearnerLoading";
import { useAuth } from "@/_core/hooks/useAuth";
import TrainingShell from "@/components/TrainingShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { appliedScenarios } from "@shared/appliedScenarios";
import { cropAdvisorCourse } from "@shared/curriculum";
import { adaptivePracticeCycle, capstoneCaseConferenceGuide, learningEnhancementBoundary, multilingualFieldCues, offlineFieldCardPack, supervisorCalibrationCases, visualCaptionTranslations } from "@shared/learningEnhancements";
import { Accessibility, BrainCircuit, ChevronRight, Download, Ear, FileText, Languages, Printer, RefreshCw, ShieldCheck, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

type Language = keyof typeof multilingualFieldCues;

export default function LearningTools() {
  const { isAuthenticated, user } = useAuth();
  const [, setLocation] = useLocation();
  const experienceQuery = trpc.learnerExperience.overview.useQuery(undefined, { enabled: isAuthenticated });
  const [language, setLanguage] = useState<Language>("english");
  const [comfortableReading, setComfortableReading] = useState(false);
  const [lowData, setLowData] = useState(false);
  const adaptiveSteps = useMemo(() => (experienceQuery.data?.nextSteps ?? []).filter(step => step.priority === "remediation" || step.priority === "practice").slice(0, 3), [experienceQuery.data?.nextSteps]);
  const scenarios = useMemo(() => Object.values(appliedScenarios).filter(scenario => ["soil-protection-runoff-decision", "nursery-batch-readiness-decision", "diagnosis-pattern-triage", "irrigation-source-performance-decision", "pest-beneficial-evidence-decision"].includes(scenario.id)), []);
  const captions = Object.entries(visualCaptionTranslations);
  const selectedCue = multilingualFieldCues[language];
  const speak = () => {
    if (!("speechSynthesis" in window)) return;
    window.speechSynthesis.cancel();
    const message = new SpeechSynthesisUtterance(["Observe. Compare. Record. Decide. Review or refer.", learningEnhancementBoundary].join(" "));
    message.lang = language === "french" ? "fr-FR" : language === "arabic" ? "ar" : "en";
    window.speechSynthesis.speak(message);
  };

  if (!isAuthenticated) return <TrainingShell><main className="mx-auto max-w-xl px-5 py-24 text-center"><BrainCircuit className="mx-auto h-10 w-10 text-[#5b8a60]" /><h1 className="mt-5 font-serif text-3xl font-semibold text-[#2f4836]">Field learning tools</h1><p className="mt-3 text-sm leading-6 text-[#617461]">Sign in to receive private adaptive practice pathways alongside the course’s printable, multilingual, and accessibility supports.</p><Button onClick={startLogin} className="mt-7 rounded-full bg-[#315f47]">Sign in to continue</Button></main></TrainingShell>;
  if (experienceQuery.isLoading) return <TrainingShell wide><LearnerLoading message="Preparing your field learning tools" /></TrainingShell>;
  if (experienceQuery.isError) return <TrainingShell><main className="mx-auto max-w-xl px-5 py-24 text-center"><RefreshCw className="mx-auto h-10 w-10 text-[#a77c36]" /><h1 className="mt-5 font-serif text-3xl font-semibold text-[#2f4836]">Learning tools are unavailable</h1><Button onClick={() => experienceQuery.refetch()} className="mt-6 rounded-full bg-[#315f47]">Retry</Button></main></TrainingShell>;

  return <TrainingShell wide><main className={`mx-auto max-w-[1420px] px-5 py-8 sm:px-8 lg:py-10 ${comfortableReading ? "text-[18px] leading-8" : ""}`}><header className="rounded-[30px] border border-[#c9dfd0] bg-[#eaf5ee] px-6 py-8 sm:px-9"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#5b806d]">Field-ready learning tools</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-[-0.05em] text-[#284d3e] sm:text-5xl">Practise, carry, explain, and review.</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#567163]">Use adaptive practice, richer cases, printable aids, language supports, and accessibility controls to transfer course learning to a careful field decision.</p></div><Badge className="border-0 bg-white px-3 py-2 text-[10px] font-bold uppercase tracking-[0.12em] text-[#4f7964]">Voluntary support</Badge></div><div className="mt-6 flex gap-2 rounded-xl border border-[#c9dece] bg-white/70 p-4"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#4d8264]" /><p className="text-xs leading-5 text-[#567061]">{learningEnhancementBoundary}</p></div></header>

    <section className="mt-7 grid gap-6 xl:grid-cols-[1.18fr_.82fr]"><article className="rounded-[24px] border border-[#dce7d9] bg-[#fcfdf9] p-6"><div className="flex items-center gap-3"><BrainCircuit className="h-5 w-5 text-[#4c835d]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#668167]">Adaptive practice</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#304d38]">Use a missed check as a practice cue.</h2></div></div><p className="mt-3 text-sm leading-6 text-[#607663]">Your private recent activity selects these optional practice routes. They guide rehearsal; they do not alter a formal score or unlock sequence.</p><div className="mt-5 space-y-3">{adaptiveSteps.length ? adaptiveSteps.map(step => <div key={step.key} className="rounded-xl border border-[#dde8dc] bg-white p-4"><p className="text-sm font-bold text-[#3b5841]">{step.title}</p><p className="mt-1 text-xs leading-5 text-[#657765]">{step.reason}</p><Button variant="outline" onClick={() => setLocation(step.href)} className="mt-3 rounded-full border-[#b9d0bf] text-xs font-bold text-[#315f47]">Open practice<ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></div>) : <div className="rounded-xl bg-[#f2f8ef] p-4 text-sm leading-6 text-[#59705a]">No recent private practice cue is available. Choose a branching case below to rehearse a decision before the next field visit.</div>}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{adaptivePracticeCycle.map(item => <div key={item.key} className="rounded-xl bg-[#f2f7ef] p-4"><p className="text-xs font-bold text-[#355b43]">{item.label}</p><p className="mt-2 text-[11px] leading-5 text-[#637664]">{item.detail}</p></div>)}</div></article>
      <aside className="rounded-[24px] border border-[#dce7d9] bg-[#fcfdf9] p-6"><div className="flex items-center gap-3"><Accessibility className="h-5 w-5 text-[#4c835d]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#668167]">Access controls</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#304d38]">Read and listen your way.</h2></div></div><div className="mt-5 space-y-3"><Button variant="outline" onClick={() => setComfortableReading(value => !value)} className="w-full justify-start rounded-xl border-[#bfd4c4] bg-white text-sm font-bold text-[#315f47]">{comfortableReading ? "Use standard reading size" : "Use comfortable reading size"}</Button><Button variant="outline" onClick={() => setLowData(value => !value)} className="w-full justify-start rounded-xl border-[#bfd4c4] bg-white text-sm font-bold text-[#315f47]">{lowData ? "Show visual cards" : "Use low-data text mode"}</Button><Button variant="outline" onClick={speak} className="w-full justify-start rounded-xl border-[#bfd4c4] bg-white text-sm font-bold text-[#315f47]"><Ear className="mr-2 h-4 w-4" />Listen to the decision cycle</Button></div><p className="mt-4 text-xs leading-5 text-[#687a69]">Listening uses the device’s available speech voice. Low-data mode keeps concise text tools available and hides optional visual-caption panels on this page.</p></aside></section>

    <section className="mt-7 rounded-[24px] border border-[#dce7d9] bg-[#fcfdf9] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#668167]">Branching field cases</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#304d38]">Test a decision against evidence and uncertainty.</h2></div><Badge className="border-0 bg-[#eef6eb] text-[10px] font-bold text-[#4c7b53]">Practice only</Badge></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{scenarios.map(scenario => <button key={scenario.id} type="button" onClick={() => setLocation(`/scenario/${scenario.id}`)} className="rounded-xl border border-[#dce7d9] bg-white p-4 text-left hover:border-[#afc9b4] hover:bg-[#f7fbf5]"><p className="text-sm font-bold text-[#3b5841]">{scenario.title.replace("Simulation: ", "")}</p><p className="mt-2 line-clamp-3 text-xs leading-5 text-[#657765]">{scenario.decisionPrompt}</p><span className="mt-3 inline-flex items-center text-xs font-bold text-[#315f47]">Open case<ChevronRight className="ml-1 h-3.5 w-3.5" /></span></button>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#dce7d9] bg-[#fcfdf9] p-6 print:border-0"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#668167]">Offline field-card pack</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#304d38]">Carry concise evidence prompts to the field.</h2></div><Button onClick={() => window.print()} className="print:hidden rounded-full bg-[#315f47] text-xs font-bold hover:bg-[#214d36]"><Printer className="mr-1.5 h-3.5 w-3.5" />Print or save PDF</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{offlineFieldCardPack.map(card => <article key={card.title} className="rounded-xl border border-[#dce7d9] bg-white p-4"><FileText className="h-4 w-4 text-[#4d8256]" /><h3 className="mt-3 text-sm font-bold text-[#3b5841]">{card.title}</h3><p className="mt-2 text-xs leading-5 text-[#657765]">{card.detail}</p><Button variant="ghost" onClick={() => setLocation(card.href)} className="mt-3 h-auto p-0 text-xs font-bold text-[#315f47] print:hidden">Open supporting tool<ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></article>)}</div></section>

    <section className="mt-7 grid gap-6 xl:grid-cols-2"><article className="rounded-[24px] border border-[#dce7d9] bg-[#fcfdf9] p-6"><div className="flex items-center gap-3"><Languages className="h-5 w-5 text-[#4c835d]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#668167]">Plain-language field cues</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#304d38]">Use the same decision cycle in three languages.</h2></div></div><div className="mt-5 flex flex-wrap gap-2">{(Object.keys(multilingualFieldCues) as Language[]).map(item => <Button key={item} variant={language === item ? "default" : "outline"} onClick={() => setLanguage(item)} className={language === item ? "rounded-full bg-[#315f47] text-xs font-bold" : "rounded-full border-[#bfd4c4] bg-white text-xs font-bold text-[#315f47]"}>{multilingualFieldCues[item].label}</Button>)}</div><div dir={selectedCue.direction} className="mt-5 flex flex-wrap gap-2">{selectedCue.phrases.map(phrase => <span key={phrase} className="rounded-full bg-[#eef6eb] px-3 py-2 text-sm font-bold text-[#395f47]">{phrase}</span>)}</div>{!lowData && <div className="mt-5 space-y-3">{captions.slice(0, 3).map(([moduleId, copy]) => <div key={moduleId} className="rounded-xl border border-[#dce7d9] bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#68816d]">{cropAdvisorCourse.modules.find(module => module.id === moduleId)?.eyebrow ?? "Module"}</p><p dir={language === "arabic" ? "rtl" : "ltr"} className="mt-2 text-xs leading-5 text-[#5e7363]">{language === "french" ? copy.french : language === "arabic" ? copy.arabic : "Select Français or العربية to view the plain-language visual caption."}</p></div>)}</div>}</article>
      <article className="rounded-[24px] border border-[#dce7d9] bg-[#fcfdf9] p-6"><div className="flex items-center gap-3"><UsersRound className="h-5 w-5 text-[#4c835d]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#668167]">Case conference and calibration</p><h2 className="mt-1 font-serif text-2xl font-semibold text-[#304d38]">Explain the decision to a grower, peer, or supervisor.</h2></div></div><div className="mt-5 space-y-3">{capstoneCaseConferenceGuide.map((item, index) => <div key={item.title} className="rounded-xl bg-[#f2f7ef] p-4"><p className="text-xs font-bold text-[#365c44]">{index + 1}. {item.title}</p><p className="mt-1 text-xs leading-5 text-[#637664]">{item.prompt}</p></div>)}</div><Button variant="outline" onClick={() => setLocation("/capstone/water-and-market-readiness")} className="mt-5 rounded-full border-[#b8d0bf] bg-white text-xs font-bold text-[#315f47]">Open capstone practice<ChevronRight className="ml-1 h-3.5 w-3.5" /></Button>{user?.role === "admin" && <div className="mt-5 border-t border-[#e1e9df] pt-5"><p className="text-xs font-bold text-[#496a51]">Supervisor calibration prompts</p><div className="mt-3 space-y-2">{supervisorCalibrationCases.map(item => <p key={item.title} className="text-xs leading-5 text-[#677969]"><span className="font-bold text-[#466b51]">{item.title}: </span>{item.detail}</p>)}</div><Button variant="ghost" onClick={() => setLocation("/supervisor/competency-calibration")} className="mt-3 h-auto p-0 text-xs font-bold text-[#315f47]">Open full calibration guide<ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></div>}</article></section>
  </main></TrainingShell>;
}
