import TrainingShell from "@/components/TrainingShell";
import { Button } from "@/components/ui/button";
import { fieldMeasurementCards, getFieldMeasurementCard } from "@shared/fieldMeasurementCards";
import { ArrowLeft, CheckCircle2, ClipboardList, Flag, Ruler, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function MeasurementCards() {
  const [, setLocation] = useLocation();
  const initialCard = typeof window === "undefined" ? undefined : new URLSearchParams(window.location.search).get("card") ?? undefined;
  const [activeId, setActiveId] = useState(getFieldMeasurementCard(initialCard).id);
  const card = getFieldMeasurementCard(activeId);

  return <TrainingShell wide><main className="mx-auto max-w-[1360px] px-5 py-8 sm:px-8 lg:py-10">
    <button type="button" onClick={() => setLocation("/field-readiness")} className="inline-flex items-center gap-2 text-xs font-bold text-[#526f55] hover:text-[#214d36]"><ArrowLeft className="h-3.5 w-3.5" />Field Readiness Portfolio</button>
    <header className="mt-5 rounded-[28px] border border-[#d8e5d3] bg-[#173c30] px-6 py-8 text-[#f7f8f1] sm:px-9"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#c6d9bc]">Field measurement and decision cards</p><h1 className="mt-3 max-w-3xl font-serif text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Measure, record, decide, review, and refer.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#d9e8d4]">These six source-grounded routines turn high-consequence field observations into bounded, traceable advisory decisions. They do not prescribe rates, certify water, approve products, or replace laboratory, label, extension, or specialist advice.</p></header>
    <div className="mt-7 grid gap-6 xl:grid-cols-[300px_1fr]">
      <aside className="xl:sticky xl:top-24 xl:h-fit"><div className="rounded-[24px] border border-[#dfe7dc] bg-[#fcfcf8] p-4"><p className="px-2 pt-1 text-[10px] font-bold uppercase tracking-[0.16em] text-[#698068]">Choose a field routine</p><div className="mt-3 space-y-2">{fieldMeasurementCards.map(item => <button key={item.id} type="button" onClick={() => setActiveId(item.id)} className={`w-full rounded-xl border p-3 text-left transition-colors ${item.id === card.id ? "border-[#7aa572] bg-[#edf6e9]" : "border-[#e0e8de] bg-[#fafcf9] hover:bg-[#f1f7ee]"}`}><Ruler className="h-4 w-4 text-[#4d7e56]" /><p className="mt-2 text-sm font-bold leading-5 text-[#38543e]">{item.shortTitle}</p><p className="mt-1 text-xs leading-5 text-[#708171]">{item.moduleIds.map(id => `Module ${id === "water-management" ? "23" : id === "drip-irrigation-system" ? "25" : id === "vegetable-fertilisation" ? "26" : id === "responsible-use-of-pesticides" ? "33" : id === "collect-soil-samples-for-soil-testing" ? "16" : id === "nutrient-management" ? "13" : "02"}`).join(" · ")}</p></button>)}</div></div></aside>
      <article className="min-w-0"><section className="rounded-[26px] border border-[#dce6d7] bg-[#edf4e9] p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#658164]">{card.sourceBasis}</p><h2 className="mt-3 font-serif text-3xl font-semibold tracking-[-0.04em] text-[#293f2e]">{card.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#58705a]">{card.purpose}</p><div className="mt-5 flex gap-3 rounded-xl border border-[#e1cfa7] bg-[#fff9ed] p-4 text-sm leading-6 text-[#75572a]"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>Decision risk:</strong> {card.risk}</p></div></section>
        <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-[22px] border border-[#dfe7dc] bg-[#fcfcf8] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#698068]">1. Prepare</p><ul className="mt-4 space-y-3">{card.prepare.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#526753]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#6f9b68]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#dfe7dc] bg-[#fcfcf8] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#698068]">2. Measure or observe</p><ol className="mt-4 space-y-3">{card.routine.map((item, index) => <li key={item} className="flex gap-3 text-sm leading-6 text-[#526753]"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#e7f1e4] text-[10px] font-bold text-[#3d7047]">{index + 1}</span>{item}</li>)}</ol></section><section className="rounded-[22px] border border-[#dfe7dc] bg-[#fcfcf8] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#698068]">3. Record the evidence</p><ul className="mt-4 space-y-3">{card.record.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#526753]"><ClipboardList className="mt-1 h-4 w-4 shrink-0 text-[#58855c]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#dfe7dc] bg-[#fcfcf8] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#698068]">4. Decide with boundaries</p><ul className="mt-4 space-y-3">{card.decide.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#526753]"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#58855c]" />{item}</li>)}</ul></section></div>
        <section className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-[22px] border border-[#d9e6d5] bg-[#f1f7ee] p-6"><Flag className="h-5 w-5 text-[#4d7e56]" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.16em] text-[#658164]">Review condition</p><p className="mt-2 text-sm leading-6 text-[#48634a]">{card.review}</p></div><div className="rounded-[22px] border border-[#eadfc7] bg-[#fffaf0] p-6"><ShieldAlert className="h-5 w-5 text-[#a57934]" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.16em] text-[#8d713f]">Stop, test, or refer</p><p className="mt-2 text-sm leading-6 text-[#755b32]">{card.refer}</p></div></section>
      </article>
    </div>
  </main></TrainingShell>;
}
