import TrainingShell from "@/components/TrainingShell";
import { getPesticideIncidentDrillStage, pesticideIncidentDrillStages } from "@shared/pesticideIncidentDrill";
import { AlertTriangle, ArrowLeft, ClipboardCheck, FileWarning, ShieldAlert, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function PesticideIncidentDrill() {
  const [, setLocation] = useLocation();
  const initialStage = typeof window === "undefined" ? undefined : new URLSearchParams(window.location.search).get("stage") ?? undefined;
  const [activeId, setActiveId] = useState(getPesticideIncidentDrillStage(initialStage).id);
  const stage = getPesticideIncidentDrillStage(activeId);

  return <TrainingShell wide><main className="mx-auto max-w-[1360px] px-5 py-8 sm:px-8 lg:py-10">
    <button type="button" onClick={() => setLocation("/field-readiness")} className="inline-flex items-center gap-2 text-xs font-bold text-[#526f55] hover:text-[#214d36]"><ArrowLeft className="h-3.5 w-3.5" />Field Readiness Portfolio</button>
    <header className="mt-5 rounded-[28px] border border-[#ead2b6] bg-[#422c25] px-6 py-8 text-[#fffaf4] sm:px-9"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f4cf9b]">Pesticide Incident Drill</p><h1 className="mt-3 max-w-3xl font-serif text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Stop, protect, escalate, and document—without improvising a high-risk response.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#f5ded0]">Use four safety stages to recognise an incident, protect people and water, consult current label-led information and authorised channels, then record and prevent recurrence. This drill never replaces current emergency, medical, legal, product-label, or employer instructions.</p></header>
    <div className="mt-5 flex gap-3 rounded-2xl border border-[#ebcfad] bg-[#fff8eb] p-4 text-sm leading-6 text-[#76542d]"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-[#a5682f]" /><p><strong>Safety boundary:</strong> If there is an exposure concern or immediate danger, use the current product label and authorised local emergency or medical channels without delay. This course drill is a decision aid for escalation and evidence, not an emergency instruction sheet.</p></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[300px_1fr]"><aside className="xl:sticky xl:top-24 xl:h-fit"><div className="rounded-[24px] border border-[#eadfd5] bg-[#fffdfa] p-4"><p className="px-2 pt-1 text-[10px] font-bold uppercase tracking-[0.16em] text-[#8b6d5a]">Choose a drill stage</p><div className="mt-3 space-y-2">{pesticideIncidentDrillStages.map(item => <button key={item.id} type="button" onClick={() => setActiveId(item.id)} className={`w-full rounded-xl border p-3 text-left transition-colors ${item.id === stage.id ? "border-[#b47852] bg-[#fff1e4]" : "border-[#eadfd5] bg-[#fffdfa] hover:bg-[#fff6ee]"}`}><ShieldAlert className="h-4 w-4 text-[#9b6044]" /><p className="mt-2 text-sm font-bold leading-5 text-[#563c31]">{item.shortTitle}</p><p className="mt-1 text-xs leading-5 text-[#8a7163]">{item.sourceBasis.split(":")[0]}</p></button>)}</div></div></aside>
      <article className="min-w-0"><section className="rounded-[26px] border border-[#eadbd0] bg-[#fff6ee] p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#9a735c]">{stage.sourceBasis}</p><h2 className="mt-3 font-serif text-3xl font-semibold tracking-[-0.04em] text-[#473329]">{stage.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#725d50]">{stage.purpose}</p><div className="mt-5 flex gap-3 rounded-xl border border-[#edcfaa] bg-[#fff8ea] p-4 text-sm leading-6 text-[#78552d]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>Why this matters:</strong> {stage.risk}</p></div></section>
        <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-[22px] border border-[#eadfd5] bg-[#fffdfa] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a6d5c]">Do now</p><ul className="mt-4 space-y-3">{stage.doNow.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#66534a]"><ShieldCheck className="mt-1 h-4 w-4 shrink-0 text-[#a26347]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#eadfd5] bg-[#fffdfa] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a6d5c]">Protect against escalation</p><ul className="mt-4 space-y-3">{stage.protect.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#66534a]"><ShieldAlert className="mt-1 h-4 w-4 shrink-0 text-[#a26347]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#eadfd5] bg-[#fffdfa] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#8a6d5c]">Record factual evidence</p><ul className="mt-4 space-y-3">{stage.record.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#66534a]"><ClipboardCheck className="mt-1 h-4 w-4 shrink-0 text-[#a26347]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#eadcc8] bg-[#fff8ed] p-6"><FileWarning className="h-5 w-5 text-[#a66b32]" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.16em] text-[#94682e]">Mandatory boundary</p><p className="mt-2 text-sm leading-6 text-[#76592f]">{stage.boundary}</p></section></div>
        <section className="mt-6 rounded-[22px] border border-[#ddded1] bg-[#f4f7f0] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#668064]">Review before future work</p><p className="mt-3 text-sm leading-6 text-[#4f664f]">{stage.followUp}</p></section>
      </article></div>
  </main></TrainingShell>;
}
