import TrainingShell from "@/components/TrainingShell";
import { getQuantifiedScoutingStage, quantifiedScoutingStages } from "@shared/quantifiedScoutingProtocol";
import { ArrowLeft, ClipboardCheck, MapPinned, Printer, Search, ShieldAlert, Target } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function QuantifiedScoutingProtocol() {
  const [, setLocation] = useLocation();
  const initialStage = typeof window === "undefined" ? undefined : new URLSearchParams(window.location.search).get("stage") ?? undefined;
  const [activeId, setActiveId] = useState(getQuantifiedScoutingStage(initialStage).id);
  const stage = getQuantifiedScoutingStage(activeId);

  return <TrainingShell wide><main className="mx-auto max-w-[1360px] px-5 py-8 sm:px-8 lg:py-10">
    <button type="button" onClick={() => setLocation("/field-readiness")} className="inline-flex items-center gap-2 text-xs font-bold text-[#526f55] hover:text-[#214d36]"><ArrowLeft className="h-3.5 w-3.5" />Field Readiness Portfolio</button>
    <header className="mt-5 rounded-[28px] border border-[#c9dfdc] bg-[#123f45] px-6 py-8 text-[#f4fbf9] sm:px-9"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#b9dbd4]">Quantified Scouting Protocol</p><h1 className="mt-3 max-w-3xl font-serif text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Make field observations comparable before they become recommendations.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#d4ebe6]">Use four repeatable stages to define a sample, record patterns and counts, protect beneficial-organism evidence, state a decision rationale, and recheck the same field evidence. The protocol supports judgement; it does not create universal thresholds or prescribe interventions.</p><button type="button" onClick={() => setLocation("/scouting-sheet")} className="mt-5 inline-flex items-center gap-2 rounded-full border border-[#a4ccc5] bg-white/10 px-4 py-2 text-xs font-bold text-white transition-colors hover:bg-white/20"><Printer className="h-3.5 w-3.5" />Print blank scouting sheet</button></header>
    <div className="mt-7 grid gap-6 xl:grid-cols-[300px_1fr]"><aside className="xl:sticky xl:top-24 xl:h-fit"><div className="rounded-[24px] border border-[#d5e5e2] bg-[#fbfdfc] p-4"><p className="px-2 pt-1 text-[10px] font-bold uppercase tracking-[0.16em] text-[#648582]">Choose a protocol stage</p><div className="mt-3 space-y-2">{quantifiedScoutingStages.map(item => <button key={item.id} type="button" onClick={() => setActiveId(item.id)} className={`w-full rounded-xl border p-3 text-left transition-colors ${item.id === stage.id ? "border-[#5a9a91] bg-[#eaf6f3]" : "border-[#dbe9e6] bg-[#fbfdfc] hover:bg-[#eef8f5]"}`}><Search className="h-4 w-4 text-[#34776f]" /><p className="mt-2 text-sm font-bold leading-5 text-[#315b57]">{item.shortTitle}</p><p className="mt-1 text-xs leading-5 text-[#6b8582]">{item.sourceBasis.split(":")[0]}</p></button>)}</div></div></aside>
      <article className="min-w-0"><section className="rounded-[26px] border border-[#d3e4e1] bg-[#eaf5f2] p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#56817b]">{stage.sourceBasis}</p><h2 className="mt-3 font-serif text-3xl font-semibold tracking-[-0.04em] text-[#294b47]">{stage.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#55716d]">{stage.purpose}</p><div className="mt-5 flex gap-3 rounded-xl border border-[#cfe1dd] bg-[#f6fbf9] p-4 text-sm leading-6 text-[#446864]"><MapPinned className="mt-0.5 h-4 w-4 shrink-0 text-[#397b73]" /><p><strong>Scouting risk:</strong> {stage.risk}</p></div></section>
        <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-[22px] border border-[#dbe9e6] bg-[#fbfdfc] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#648582]">Prepare the sample</p><ul className="mt-4 space-y-3">{stage.prepare.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#4d6865]"><Target className="mt-1 h-4 w-4 shrink-0 text-[#3e877d]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#dbe9e6] bg-[#fbfdfc] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#648582]">Observe the pattern</p><ul className="mt-4 space-y-3">{stage.observe.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#4d6865]"><Search className="mt-1 h-4 w-4 shrink-0 text-[#3e877d]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#dbe9e6] bg-[#fbfdfc] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#648582]">Quantify consistently</p><ul className="mt-4 space-y-3">{stage.quantify.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#4d6865]"><ClipboardCheck className="mt-1 h-4 w-4 shrink-0 text-[#3e877d]" />{item}</li>)}</ul></section><section className="rounded-[22px] border border-[#dbe9e6] bg-[#fbfdfc] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#648582]">Record the evidence</p><ul className="mt-4 space-y-3">{stage.record.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#4d6865]"><ClipboardCheck className="mt-1 h-4 w-4 shrink-0 text-[#3e877d]" />{item}</li>)}</ul></section></div>
        <section className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-[22px] border border-[#cbdeda] bg-[#f0f8f5] p-6"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#5f817b]">Recheck standard</p><p className="mt-3 text-sm leading-6 text-[#466761]">{stage.review}</p></div><div className="rounded-[22px] border border-[#eadfc5] bg-[#fffaf0] p-6"><ShieldAlert className="h-5 w-5 text-[#a67933]" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.16em] text-[#8e713e]">Decision and referral boundary</p><p className="mt-2 text-sm leading-6 text-[#765a31]">{stage.decisionBoundary}</p><p className="mt-4 border-t border-[#eadfc5] pt-4 text-sm leading-6 text-[#765a31]">{stage.refer}</p></div></section>
      </article></div>
  </main></TrainingShell>;
}
