import TrainingShell from "@/components/TrainingShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createEmptyRootZoneWaterDecisionDraft, hasComparableRootZoneWaterEvidence, rootZoneWaterDecisionLabRequirements, type RootZoneWaterDecisionDraft, type RootZoneWaterEvidenceCheckId } from "@shared/rootZoneWaterDecisionLab";
import { ArrowLeft, CheckCircle2, ClipboardCheck, FileDown, ShieldCheck, Waves } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function RootZoneWaterDecisionLab() {
  const [, setLocation] = useLocation();
  const [draft, setDraft] = useState(createEmptyRootZoneWaterDecisionDraft);
  const ready = hasComparableRootZoneWaterEvidence(draft);
  const updateObservation = (index: number, field: "location" | "rootZoneAndAir" | "cropAndPattern", value: string) => setDraft(current => ({ ...current, observations: current.observations.map((observation, observationIndex) => observationIndex === index ? { ...observation, [field]: value } : observation) }));
  const updateCheck = (id: RootZoneWaterEvidenceCheckId, value: boolean) => setDraft(current => ({ ...current, evidenceChecks: { ...current.evidenceChecks, [id]: value } }));

  return <TrainingShell wide><main className="mx-auto max-w-[1200px] px-5 py-7 sm:px-8 lg:py-9 print:max-w-none print:px-0"><button type="button" onClick={() => setLocation("/course/water-management")} className="inline-flex items-center gap-1.5 text-xs font-bold text-[#59705e] hover:text-[#1f4a37]"><ArrowLeft className="h-3.5 w-3.5" />Back to Module 23</button>
    <header className="mt-5 rounded-[28px] border border-[#cfe1d0] bg-[#eef7ec] px-6 py-7 sm:px-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge className="border-0 bg-white text-[10px] font-bold uppercase tracking-[0.15em] text-[#4a7753]">Voluntary field practice</Badge><h1 className="mt-4 max-w-3xl font-serif text-4xl font-semibold tracking-[-0.055em] text-[#294a39]">Root-Zone Water and Air Lab</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#557057]">Compare field zones through the root zone: water context, soil-air or drainage clues, crop response, and the safest evidence-led next check.</p></div><Waves className="h-9 w-9 text-[#4d8156]" /></div><p className="mt-5 flex gap-2 rounded-xl border border-[#cae0cc] bg-white/75 p-4 text-xs leading-5 text-[#527056]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#4b8054]" />{rootZoneWaterDecisionLabRequirements.safetyBoundary}</p></header>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><Waves className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 1 · Frame the water question</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Start with context, not an assumed water problem.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Bring together crop stage, root-zone conditions, rainfall or irrigation history, and field pattern before interpreting one visible symptom.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="water-lab-question">Field question</Label><Textarea id="water-lab-question" value={draft.fieldQuestion} onChange={event => setDraft(current => ({ ...current, fieldQuestion: event.target.value }))} placeholder="For example: What evidence explains different crop response across these two zones?" className="mt-2 min-h-24 bg-white text-sm" /></div><div className="space-y-4"><div><Label htmlFor="water-lab-stage">Crop stage and observation context</Label><Input id="water-lab-stage" value={draft.cropStage} onChange={event => setDraft(current => ({ ...current, cropStage: event.target.value }))} placeholder="Enter crop stage and observation date" className="mt-2 bg-white" /></div><div><Label htmlFor="water-lab-history">Recent rainfall, irrigation, or source context</Label><Textarea id="water-lab-history" value={draft.recentWaterContext} onChange={event => setDraft(current => ({ ...current, recentWaterContext: event.target.value }))} placeholder="Record events and system context without assuming they caused the pattern." className="mt-2 min-h-20 bg-white text-sm" /></div></div></div></section>

    <section className="mt-7 rounded-[24px] border border-[#d8e6d6] bg-[#f7fbf4] p-5 sm:p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 2 · Compare the root zone</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Observe water and air clues in both zones.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Record what you can observe. Avoid converting moisture, plant stress, or a wet area into a final diagnosis.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2">{draft.observations.map((observation, index) => <article key={observation.zone} className="rounded-xl border border-[#dce8d9] bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#648066]">Comparison {index + 1}</p><h3 className="mt-2 font-serif text-xl font-semibold text-[#34513c]">{observation.zone}</h3><div className="mt-4 space-y-3"><div><Label htmlFor={`water-lab-location-${index}`} className="text-xs">Location / map cue</Label><Input id={`water-lab-location-${index}`} value={observation.location} onChange={event => updateObservation(index, "location", event.target.value)} placeholder="Row, zone, slope, inlet, or far-end cue" className="mt-1.5 bg-white text-sm" /></div><div><Label htmlFor={`water-lab-root-${index}`} className="text-xs">Root-zone water and air / drainage clues</Label><Textarea id={`water-lab-root-${index}`} value={observation.rootZoneAndAir} onChange={event => updateObservation(index, "rootZoneAndAir", event.target.value)} placeholder="Soil feel, moisture distribution, drainage, rooting, ponding, crusting, or compaction observations." className="mt-1.5 min-h-28 bg-white text-sm" /></div><div><Label htmlFor={`water-lab-pattern-${index}`} className="text-xs">Crop response and pattern</Label><Textarea id={`water-lab-pattern-${index}`} value={observation.cropAndPattern} onChange={event => updateObservation(index, "cropAndPattern", event.target.value)} placeholder="Describe crop stage, plant response, field distribution, and what differs from the comparison zone." className="mt-1.5 min-h-24 bg-white text-sm" /></div></div></article>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 3 · Verify before changing a system</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Complete the evidence check.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">A system setting is not the starting point. Confirm comparable evidence before changing runtime, pressure, schedule, or another operating condition.</p></div></div><div className="mt-5 space-y-3">{rootZoneWaterDecisionLabRequirements.evidenceChecks.map(check => <label key={check.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-[#dce8d9] bg-[#f8fbf6] p-4 transition-colors hover:bg-white"><input type="checkbox" checked={draft.evidenceChecks[check.id]} onChange={event => updateCheck(check.id, event.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-[#4b8054]" /><span className="text-sm leading-6 text-[#49614e]">{check.label}</span></label>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#cfe1d0] bg-[#eef7ec] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#618164]">Step 4 · Recheck or refer</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Choose the safest evidence-led next step.</h2></div><Button type="button" onClick={() => window.print()} variant="outline" className="rounded-full border-[#9db99d] bg-white text-xs font-bold text-[#315f47]"><FileDown className="mr-1.5 h-3.5 w-3.5" />Print water draft</Button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="water-lab-next">Next step</Label><select id="water-lab-next" value={draft.nextStep} onChange={event => setDraft(current => ({ ...current, nextStep: event.target.value as RootZoneWaterDecisionDraft["nextStep"] }))} className="mt-2 flex h-10 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50">{rootZoneWaterDecisionLabRequirements.nextStepOptions.map(step => <option key={step}>{step}</option>)}</select></div><div><Label htmlFor="water-lab-pause">Reason to pause, recheck, or refer</Label><Textarea id="water-lab-pause" value={draft.pauseOrReferral} onChange={event => setDraft(current => ({ ...current, pauseOrReferral: event.target.value }))} placeholder="Record the uncertainty, risk, or missing evidence that prevents a final water-management conclusion." className="mt-2 min-h-20 bg-white text-sm" /></div></div><div className="mt-5 rounded-xl border border-[#d6e5d4] bg-white/85 p-4"><p className="flex items-center gap-2 text-sm font-bold text-[#426247]"><CheckCircle2 className="h-4 w-4 text-[#4b8054]" />Evidence-check status: {ready ? "Comparable water and root-zone evidence recorded" : "Complete the context, both zone comparisons, and all evidence checks"}</p><p className="mt-2 text-xs leading-5 text-[#5c735f]">{rootZoneWaterDecisionLabRequirements.nonGatingBoundary}</p></div></section>
  </main></TrainingShell>;
}
