import { useAuth } from "@/_core/hooks/useAuth";
import LearnerLoading from "@/components/LearnerLoading";
import TrainingShell from "@/components/TrainingShell";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { cropAdvisorCourse } from "@shared/curriculum";
import { CheckCircle2, ClipboardPenLine, MessageSquareText } from "lucide-react";
import { useLocation } from "wouter";

export default function ScorecardReflectionLibrary() {
  const { isAuthenticated } = useAuth();
  const [, setLocation] = useLocation();
  const scorecardsQuery = trpc.competencyAssessments.mine.useQuery(undefined, { enabled: isAuthenticated });
  if (!isAuthenticated) return <TrainingShell><main className="mx-auto max-w-xl px-5 py-24 text-center"><ClipboardPenLine className="mx-auto h-10 w-10 text-[#5d8b61]" /><h1 className="mt-5 font-serif text-3xl font-semibold text-[#2f4836]">Scorecard reflections</h1><p className="mt-3 text-sm leading-6 text-[#617461]">Sign in to revisit your private supervisor scorecards and reflections.</p><Button onClick={startLogin} className="mt-6 rounded-full bg-[#315f47]">Sign in to continue</Button></main></TrainingShell>;
  if (scorecardsQuery.isLoading) return <TrainingShell wide><LearnerLoading message="Opening your scorecard reflections" /></TrainingShell>;
  if (scorecardsQuery.isError) return <TrainingShell><main className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="font-serif text-3xl font-semibold text-[#2f4836]">Scorecards unavailable</h1><Button onClick={() => scorecardsQuery.refetch()} className="mt-6 rounded-full bg-[#315f47]">Retry</Button></main></TrainingShell>;
  const scorecards = (scorecardsQuery.data ?? []).filter(item => Boolean(item.scorecard && item.feedback));
  return <TrainingShell wide><main className="mx-auto max-w-[1080px] px-5 py-8 sm:px-8 lg:py-10"><header className="rounded-[28px] border border-[#cde0ce] bg-[#edf6e9] p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#608060]">Private reflection library</p><h1 className="mt-2 font-serif text-3xl font-semibold tracking-[-0.045em] text-[#2c4a35] sm:text-4xl">Reconnect every scorecard to your next evidence step.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#536b55]">Open any scored module to revisit feedback, record a reflection, and identify evidence for the next review. Reflections are developmental and do not change formal progression.</p></header><section className="mt-7 grid gap-4 md:grid-cols-2">{scorecards.length ? scorecards.map(assessment => { const module = cropAdvisorCourse.modules.find(item => item.id === assessment.moduleId); return <article key={assessment.id} className="rounded-[22px] border border-[#dce7d9] bg-[#fcfdf9] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#698169]">{module?.eyebrow ?? "Module"}</p><h2 className="mt-1 text-lg font-bold text-[#385640]">{module?.title ?? assessment.moduleId}</h2></div><span className={assessment.status === "revision_requested" ? "rounded-full bg-[#fff0df] px-2.5 py-1 text-[10px] font-bold text-[#9a6337]" : "rounded-full bg-[#e3f1e2] px-2.5 py-1 text-[10px] font-bold text-[#3c7749]"}>{assessment.status === "revision_requested" ? "Revision requested" : "Scored"}</span></div><p className="mt-4 line-clamp-3 text-sm leading-6 text-[#617461]">{assessment.feedback}</p><Button variant="outline" onClick={() => setLocation(`/competency-reflection/${assessment.id}`)} className="mt-5 rounded-full border-[#b9cfb6] bg-white text-xs font-bold text-[#315f47] hover:bg-[#edf5e9]"><ClipboardPenLine className="mr-1.5 h-3.5 w-3.5" />Open reflection</Button></article>; }) : <div className="rounded-[22px] border border-[#dce7d9] bg-[#fcfdf9] p-8 md:col-span-2"><MessageSquareText className="h-7 w-7 text-[#619267]" /><h2 className="mt-4 font-serif text-2xl font-semibold text-[#304b38]">No scored module evidence yet.</h2><p className="mt-2 text-sm leading-6 text-[#617461]">Once a supervisor saves a scorecard and feedback, its reflection prompts will appear here.</p><Button onClick={() => setLocation("/competencies")} className="mt-5 rounded-full bg-[#315f47]"><CheckCircle2 className="mr-1.5 h-3.5 w-3.5" />Open competency map</Button></div>}</section></main></TrainingShell>;
}
