import TrainingShell from "@/components/TrainingShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createEmptySoilSamplingAuditDraft, getMissingSoilSamplingAuditChecks, isSoilSamplingAuditReady, soilSamplingQualityAuditRequirements, type SoilSamplingAuditCheckId } from "@shared/soilSamplingQualityAudit";
import { ArrowLeft, ClipboardCheck, FileDown, FlaskConical, MapPinned, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const zoneExamples = [
  ["Zone A · uniform vegetable beds", "Keep this as one proposed sampling unit only if crop, management, and soil conditions are genuinely comparable."],
  ["Zone B · low or poorly drained corner", "Map and keep separate from the central beds; this field difference may change the question sent to the laboratory."],
  ["Zone C · recently changed management area", "Map and keep separate where amendments, crops, water movement, or management history differs."],
] as const;

export default function SoilSamplingQualityAudit() {
  const [, setLocation] = useLocation();
  const [draft, setDraft] = useState(createEmptySoilSamplingAuditDraft);
  const missingChecks = getMissingSoilSamplingAuditChecks(draft);
  const ready = isSoilSamplingAuditReady(draft);
  const updateCheck = (id: SoilSamplingAuditCheckId, checked: boolean) => setDraft(current => ({ ...current, checks: { ...current.checks, [id]: checked } }));

  return <TrainingShell wide><main className="mx-auto max-w-[1200px] px-5 py-7 sm:px-8 lg:py-9 print:max-w-none print:px-0"><button type="button" onClick={() => setLocation("/course/collect-soil-samples-for-soil-testing")} className="inline-flex items-center gap-1.5 text-xs font-bold text-[#59705e] hover:text-[#1f4a37]"><ArrowLeft className="h-3.5 w-3.5" />Back to Module 16</button>
    <header className="mt-5 rounded-[28px] border border-[#cfe1d0] bg-[#eef7ec] px-6 py-7 sm:px-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge className="border-0 bg-white text-[10px] font-bold uppercase tracking-[0.15em] text-[#4a7753]">Voluntary field practice</Badge><h1 className="mt-4 max-w-3xl font-serif text-4xl font-semibold tracking-[-0.055em] text-[#294a39]">Soil Sampling Quality Audit</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#557057]">Check whether a planned sample is representative, traceable, cleanly handled, and ready for the receiving laboratory’s current method.</p></div><FlaskConical className="h-9 w-9 text-[#4d8156]" /></div><p className="mt-5 flex gap-2 rounded-xl border border-[#cae0cc] bg-white/75 p-4 text-xs leading-5 text-[#527056]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#4b8054]" />{soilSamplingQualityAuditRequirements.safetyBoundary}</p></header>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><MapPinned className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 1 · Map before mixing</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Separate unlike field conditions into clear sample questions.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">A composite sample is useful only when the points represent a comparable management area. Map differences first rather than hiding them in one bag.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-3">{zoneExamples.map(([title, description]) => <article key={title} className="rounded-xl border border-[#dce8d9] bg-[#f8fbf6] p-4"><p className="text-sm font-bold text-[#395842]">{title}</p><p className="mt-2 text-xs leading-5 text-[#5a705d]">{description}</p></article>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#d8e6d6] bg-[#f7fbf4] p-5 sm:p-6"><div className="flex items-start gap-3"><ClipboardCheck className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 2 · Build the sample identity</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Make the bag, field record, and laboratory request agree.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Use the receiving laboratory’s current form and method. This draft records the information that makes a result traceable; it does not replace the laboratory form.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label htmlFor="soil-audit-id">Unique sample identity</Label><Input id="soil-audit-id" value={draft.sampleId} onChange={event => setDraft(current => ({ ...current, sampleId: event.target.value }))} placeholder="Enter your sample ID" className="mt-2 bg-white" /></div><div><Label htmlFor="soil-audit-zone">Field or management zone</Label><Input id="soil-audit-zone" value={draft.fieldZone} onChange={event => setDraft(current => ({ ...current, fieldZone: event.target.value }))} placeholder="Enter mapped zone and location cue" className="mt-2 bg-white" /></div><div><Label htmlFor="soil-audit-question">Crop, history, and laboratory question</Label><Textarea id="soil-audit-question" value={draft.cropAndQuestion} onChange={event => setDraft(current => ({ ...current, cropAndQuestion: event.target.value }))} placeholder="Record crop or intended crop, relevant management history, and the question needing laboratory evidence." className="mt-2 min-h-24 bg-white text-sm" /></div><div><Label htmlFor="soil-audit-instructions">Receiving laboratory instructions confirmed</Label><Textarea id="soil-audit-instructions" value={draft.labInstructions} onChange={event => setDraft(current => ({ ...current, labInstructions: event.target.value }))} placeholder="Record the current laboratory method, sample form, handling direction, and any instruction that applies to this sample." className="mt-2 min-h-24 bg-white text-sm" /></div></div></section>

    <section className="mt-7 rounded-[24px] border border-[#dce8da] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><FlaskConical className="mt-0.5 h-5 w-5 text-[#4c7e55]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#638267]">Step 3 · Quality gate</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Audit the sampling chain before submission.</h2><p className="mt-2 text-sm leading-6 text-[#5c715f]">Check each control only when it has been verified in the field or against the receiving laboratory’s current instructions.</p></div></div><div className="mt-5 space-y-3">{soilSamplingQualityAuditRequirements.auditChecks.map(check => <label key={check.id} className="flex cursor-pointer items-start gap-3 rounded-xl border border-[#dce8d9] bg-[#f8fbf6] p-4 transition-colors hover:bg-white"><input type="checkbox" checked={draft.checks[check.id]} onChange={event => updateCheck(check.id, event.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-[#4b8054]" /><span className="text-sm leading-6 text-[#49614e]">{check.label}</span></label>)}</div></section>

    <section className="mt-7 rounded-[24px] border border-[#cfe1d0] bg-[#eef7ec] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#618164]">Step 4 · Pause, clarify, or submit</p><h2 className="mt-2 font-serif text-2xl font-semibold tracking-[-0.04em] text-[#2f4c38]">Do not send an uncertain sample forward without context.</h2></div><Button type="button" onClick={() => window.print()} variant="outline" className="rounded-full border-[#9db99d] bg-white text-xs font-bold text-[#315f47]"><FileDown className="mr-1.5 h-3.5 w-3.5" />Print quality draft</Button></div><div className="mt-5"><Label htmlFor="soil-audit-pause">Reason to pause, resample, or seek laboratory / extension clarification</Label><Textarea id="soil-audit-pause" value={draft.pauseOrReferral} onChange={event => setDraft(current => ({ ...current, pauseOrReferral: event.target.value }))} placeholder="Record any mixed zones, unclear history, tool contamination, lab-instruction uncertainty, or result question that needs clarification." className="mt-2 min-h-24 bg-white text-sm" /></div><div className="mt-5 rounded-xl border border-[#d6e5d4] bg-white/85 p-4"><p className="text-sm font-bold text-[#426247]">Quality status: {ready ? "Ready to compare with the receiving laboratory instructions" : `Complete ${missingChecks.length} remaining sampling control${missingChecks.length === 1 ? "" : "s"} and the identity fields`}</p><p className="mt-2 text-xs leading-5 text-[#5c735f]">{soilSamplingQualityAuditRequirements.nonGatingBoundary}</p></div></section>
  </main></TrainingShell>;
}
