export type CompetencyDomain = {
  id: string;
  title: string;
  purpose: string;
  fieldStatement: string;
};

export type ModuleCompetency = {
  moduleId: string;
  domainId: string;
  title: string;
  competencyStatement: string;
  performanceTask: string;
  evidence: string;
  criteria: readonly string[];
  remediationFocus: string;
  safetyBoundary: string;
};

export const competencyDomains: readonly CompetencyDomain[] = [
  { id: "advisory-judgement", title: "Advisory judgement and professional practice", purpose: "Frame crop decisions, distinguish evidence from inference, communicate clearly, and set review or referral boundaries.", fieldStatement: "I can turn a grower question into a transparent, reviewable field decision without claiming more certainty than the evidence supports." },
  { id: "site-soil-crop-analysis", title: "Site, soil, and crop-performance analysis", purpose: "Read crop, soil, climate, terrain, and root-zone conditions as connected production constraints.", fieldStatement: "I can compare field zones and identify the evidence needed to test the leading crop-performance limitation." },
  { id: "farm-planning-economics", title: "Farm planning, crop fit, and economics", purpose: "Match production choices to context, resources, market, and risk rather than applying generic plans.", fieldStatement: "I can explain a crop-production choice with its practical, economic, and uncertainty conditions." },
  { id: "soil-nutrient-stewardship", title: "Soil and nutrient stewardship", purpose: "Collect representative evidence, protect soil function, and make cautious nutrient-management decisions.", fieldStatement: "I can plan, record, and review soil and nutrient actions using field and laboratory evidence with stated assumptions." },
  { id: "nursery-establishment", title: "Nursery quality and crop establishment", purpose: "Protect seedling quality, transplant acceptance, and early stand performance.", fieldStatement: "I can inspect, accept or hold, establish, and review seedlings using traceable quality evidence." },
  { id: "water-irrigation", title: "Water and irrigation performance", purpose: "Assess water-air balance, delivery performance, and irrigation decisions across crop stage and field variation.", fieldStatement: "I can measure, compare, and review water or irrigation evidence before proposing a practical next step." },
  { id: "crop-care-quality", title: "Crop care, harvest, and market quality", purpose: "Protect crop structure, market quality, hygiene, handling, and traceability through the production cycle.", fieldStatement: "I can prioritise an operational crop-care or harvest-quality risk and specify evidence for its review." },
  { id: "crop-health-stewardship", title: "Crop health, IPM, and pesticide stewardship", purpose: "Use quantified observation, competing explanations, prevention, and lawful escalation boundaries for crop-health decisions.", fieldStatement: "I can separate symptoms, pests, beneficials, patterns, and uncertainty before selecting a low-risk IPM or referral next step." },
] as const;

export const competencyPerformanceLevels = [
  { id: "prepare", label: "Prepare", description: "Frames the task, selects a suitable method, and names the evidence and safety conditions required before acting." },
  { id: "perform", label: "Perform", description: "Completes the observable field task or decision sequence using traceable evidence rather than unsupported assumptions." },
  { id: "review-refer", label: "Review and refer", description: "Sets a follow-up indicator, interprets uncertainty, and revises, stops, or refers when the evidence or risk requires it." },
] as const;

export const moduleCompetencies: readonly ModuleCompetency[] = [
  { moduleId: "advisory-practice", domainId: "advisory-judgement", title: "Frame a defensible advisory decision", competencyStatement: "Convert a grower question into an evidence-led, reviewable advisory decision.", performanceTask: "Create a field-visit decision note that separates observations, reports, assumptions, recommendation conditions, and follow-up.", evidence: "Field question, affected/unaffected comparison, decision rationale, constraint, recheck trigger, and referral boundary.", criteria: ["States the decision before proposing an action.", "Separates observation, report, inference, and uncertainty.", "Names a practical follow-up or referral condition."], remediationFocus: "Rebuild the note from observation to decision before revisiting the module check.", safetyBoundary: "Defer or refer high-consequence decisions when evidence, authority, or competence is insufficient." },
  { moduleId: "soil-and-nutrition", domainId: "site-soil-crop-analysis", title: "Interpret soil context before nutrient action", competencyStatement: "Use rooting, water, structure, and representative sampling context to test a nutrient-management question.", performanceTask: "Plan a zone-based soil and crop observation with a justified sampling approach.", evidence: "Zone sketch, rooting or water observations, sample plan, laboratory-context assumptions, and review point.", criteria: ["Compares materially different zones.", "Explains why root-zone evidence changes interpretation.", "States sampling limits and next checks."], remediationFocus: "Practise distinguishing nutrient symptoms from root-zone and water constraints.", safetyBoundary: "Do not convert a field symptom or report into a nutrient prescription without current local interpretation and supporting evidence." },
  { moduleId: "crop-observation", domainId: "site-soil-crop-analysis", title: "Conduct structured crop observation", competencyStatement: "Observe crop condition systematically and record patterns that can support later diagnosis or management review.", performanceTask: "Use a repeatable observation route to compare plant condition, distribution, stage, and likely contributing context.", evidence: "Observation route, field pattern, comparison plants, growth-stage note, image or sketch where authorised, and uncertainty record.", criteria: ["Uses more than one field position.", "Records distribution and comparison evidence.", "Avoids naming a cause beyond the observation."], remediationFocus: "Repeat the route using the observation-versus-interpretation distinction.", safetyBoundary: "A visual observation is not a confirmed diagnosis or treatment authority." },
  { moduleId: "vegetable-production-planning", domainId: "farm-planning-economics", title: "Build a context-fit vegetable production plan", competencyStatement: "Translate crop, site, season, resource, and market context into a feasible production sequence.", performanceTask: "Prepare a simple production calendar with key decisions, evidence checks, labour or input assumptions, and review dates.", evidence: "Crop-stage calendar, resource assumptions, market or household purpose, risk points, and review schedule.", criteria: ["Links actions to crop stage and context.", "Makes resource assumptions visible.", "Includes a revision point for changing conditions."], remediationFocus: "Rework the calendar around one clear crop stage and one limiting resource.", safetyBoundary: "Do not present local prices, varieties, or timing as universal recommendations; verify current local information." },
  { moduleId: "cost-planning-and-decisions", domainId: "farm-planning-economics", title: "Compare farm decisions with uncertainty", competencyStatement: "Use transparent cost, labour, benefit, and downside assumptions to support a crop decision.", performanceTask: "Compare a proposed action with a lower-risk alternative and explain the assumption most likely to change the decision.", evidence: "Cost or labour estimate, expected benefit, downside risk, alternative action, and follow-up measure.", criteria: ["Distinguishes fact from assumption.", "Includes labour and downside risk.", "Names the evidence that would revise the choice."], remediationFocus: "Practise a two-option comparison before selecting an input or activity.", safetyBoundary: "Do not provide fixed prices, profitability promises, or financial advice without dated local evidence." },
  { moduleId: "crop-and-variety-selection", domainId: "farm-planning-economics", title: "Match crop and variety choice to context", competencyStatement: "Explain a crop or variety choice using production conditions, market purpose, resilience needs, and uncertainty.", performanceTask: "Create a crop-fit comparison for a stated site and market context.", evidence: "Site and season factors, crop purpose, variety criteria, constraints, current local source, and review point.", criteria: ["Uses stated selection criteria.", "Connects choice to context rather than preference.", "Identifies a local fact that needs verification."], remediationFocus: "Revisit crop-fit criteria and distinguish them from product or variety promotion.", safetyBoundary: "Verify current seed availability, approved varieties, and local recommendations through authorised sources." },
  { moduleId: "factors-affecting-crop-yield", domainId: "site-soil-crop-analysis", title: "Prioritise crop-yield constraints", competencyStatement: "Identify linked yield constraints and select the evidence needed to test the most limiting factor.", performanceTask: "Produce a yield-constraint map that ranks possible soil, water, crop, climate, and management limitations.", evidence: "Constraint map, comparison evidence, priority rationale, uncertainty note, and recheck plan.", criteria: ["Considers interacting constraints.", "Prioritises rather than lists every factor.", "Sets evidence to confirm or revise the priority."], remediationFocus: "Practise ranking a field issue instead of treating every symptom as equally important.", safetyBoundary: "Avoid claiming a single cause of low yield without field evidence and appropriate measurement." },
  { moduleId: "climatic-factors-affecting-crop-yield", domainId: "site-soil-crop-analysis", title: "Use climate evidence in crop decisions", competencyStatement: "Relate crop stage and local weather exposure to practical risk-reduction and review actions.", performanceTask: "Prepare a crop-stage climate-risk note using a dated forecast or recorded weather source.", evidence: "Crop stage, weather source/date, exposure, feasible response, uncertainty, and review trigger.", criteria: ["Uses dated weather evidence.", "Relates exposure to crop stage.", "States a condition requiring plan revision."], remediationFocus: "Practise interpreting climate risk as a decision condition rather than a fixed calendar rule.", safetyBoundary: "Do not represent a forecast as certain or prescribe unverified local weather responses." },
  { moduleId: "topographic-factors-affecting-crop-yield", domainId: "site-soil-crop-analysis", title: "Read terrain-linked production risk", competencyStatement: "Use slope, elevation, runoff, drainage, and field position evidence to explain production variation.", performanceTask: "Annotate a field sketch showing terrain-linked zones and their scouting or management implications.", evidence: "Field sketch, slope or runoff observations, zone comparisons, risk statement, and follow-up check.", criteria: ["Connects landform to observable water or soil effects.", "Separates zones before drawing conclusions.", "States a practical measurement or observation to review."], remediationFocus: "Revisit the zone sketch and compare high-risk and lower-risk positions.", safetyBoundary: "Do not make engineering or drainage prescriptions without suitable site assessment and authorised expertise." },
  { moduleId: "edaphic-soil-factors-affecting-crop-yield", domainId: "site-soil-crop-analysis", title: "Assess edaphic constraints", competencyStatement: "Interpret physical, chemical, and biological soil evidence as linked influences on crop yield.", performanceTask: "Complete a soil-function observation note that identifies a dominant constraint and evidence gap.", evidence: "Soil description, root or moisture observation, test context, dominant constraint rationale, and review plan.", criteria: ["Includes physical and biological context.", "Avoids treating a test result in isolation.", "Identifies an evidence limit."], remediationFocus: "Practise combining soil observation with laboratory or crop evidence.", safetyBoundary: "Do not infer soil amendment needs from a single symptom or generic threshold." },
  { moduleId: "soil-degradation-and-management", domainId: "soil-nutrient-stewardship", title: "Plan soil-protection action", competencyStatement: "Identify soil-degradation risks and frame a protective action with measurable review indicators.", performanceTask: "Create a soil-protection plan for a documented erosion, compaction, cover, or organic-matter risk.", evidence: "Risk observation, affected area, causal conditions, feasible protective action, measurement, and follow-up date.", criteria: ["Links action to observed degradation risk.", "Includes a feasible field measure.", "Accounts for timing and operational constraints."], remediationFocus: "Rebuild the plan around one observable risk and one measurable outcome.", safetyBoundary: "Do not prescribe site-specific earthworks or structural interventions without competent local assessment." },
  { moduleId: "nutrients-required-in-plant-nutrition", domainId: "soil-nutrient-stewardship", title: "Interpret nutrient roles cautiously", competencyStatement: "Connect nutrient function, uptake conditions, and crop symptoms without over-diagnosing deficiency.", performanceTask: "Explain competing nutrient and non-nutrient explanations for a crop observation and select the next evidence step.", evidence: "Symptom description, crop part and pattern, root or water context, competing explanations, and next test.", criteria: ["Separates nutrient function from confirmed deficiency.", "Includes uptake conditions.", "Selects a defensible next evidence step."], remediationFocus: "Practise symptom description and competing explanations before naming nutrients.", safetyBoundary: "Leaf colour or a photograph alone is not authority for a nutrient product or rate." },
  { moduleId: "nutrient-management", domainId: "soil-nutrient-stewardship", title: "Build an integrated nutrient-management plan", competencyStatement: "Build a nutrient-management decision that integrates crop demand, soil evidence, source, timing, and review.", performanceTask: "Draft an integrated nutrient plan with stated 4R-style assumptions and response monitoring.", evidence: "Soil or crop evidence, crop stage, source assumptions, placement/timing considerations, constraints, and review measure.", criteria: ["Connects plan to evidence and crop demand.", "States assumptions and constraints.", "Defines response or risk monitoring."], remediationFocus: "Use the nutrient-plan evidence card before attempting the formal check again.", safetyBoundary: "Use current local laboratory interpretation, lawful product information, and authorised advice for any rate or product decision." },
  { moduleId: "acid-soil-causes-and-management", domainId: "soil-nutrient-stewardship", title: "Assess acid-soil risk", competencyStatement: "Use pH and field context to frame acid-soil risk and a measured management or referral pathway.", performanceTask: "Prepare a pH-risk interpretation note that distinguishes test evidence, crop context, and management uncertainty.", evidence: "Sample context, pH or related evidence, crop sensitivity, field variability, current interpretation source, and review plan.", criteria: ["Preserves sample and field context.", "Names the evidence limit.", "Uses a current local interpretation source."], remediationFocus: "Revisit sample quality and interpretation assumptions before planning a response.", safetyBoundary: "Do not prescribe amendment materials or rates without current local laboratory and authorised guidance." },
  { moduleId: "how-to-promote-soil-health", domainId: "soil-nutrient-stewardship", title: "Build soil-health improvement evidence", competencyStatement: "Select and review soil-health practices using observable soil-function and production evidence.", performanceTask: "Develop a soil-health trial or improvement note with baseline, practice, indicator, and review period.", evidence: "Baseline condition, selected practice, indicator, time frame, labour or cost constraint, and review evidence.", criteria: ["Names a measurable soil-function indicator.", "Connects practice to an observed need.", "Plans a realistic review period."], remediationFocus: "Reduce the plan to one practice and one indicator that can be revisited.", safetyBoundary: "Avoid universal soil-health claims; field response depends on context and needs review." },
  { moduleId: "collect-soil-samples-for-soil-testing", domainId: "soil-nutrient-stewardship", title: "Collect representative soil samples", competencyStatement: "Plan, collect, label, and document representative soil samples for a defined management question.", performanceTask: "Complete a representative sample plan and sample-chain record for field zones.", evidence: "Question, zones, depths, core route, exclusions, labels, date, tools, and laboratory hand-off record.", criteria: ["Matches sampling plan to decision.", "Prevents cross-zone or contamination bias.", "Preserves traceability from field to laboratory."], remediationFocus: "Repeat the representative-sampling measurement card and compare zone decisions.", safetyBoundary: "Follow current laboratory instructions and local interpretation protocols; do not create unverified sampling rules." },
  { moduleId: "nursery-for-vegetable-production", domainId: "nursery-establishment", title: "Inspect nursery quality", competencyStatement: "Assess nursery hygiene, seedling quality, and batch traceability before plants move to the field.", performanceTask: "Complete a nursery batch and daily quality check, then decide accept, hold, or seek support.", evidence: "Batch identity, hygiene or environment observations, seedling quality indicators, decision, and follow-up.", criteria: ["Keeps batch and condition evidence linked.", "Uses accept/hold reasoning.", "Records an escalation condition."], remediationFocus: "Use the nursery quality routine and document one complete inspection cycle.", safetyBoundary: "Do not make disease, chemical, or seed-treatment claims without verified evidence and authorised guidance." },
  { moduleId: "open-field-seedling-production", domainId: "nursery-establishment", title: "Manage open-field seedling production", competencyStatement: "Plan, observe, and review bare-root nursery production for uniformity and transplant readiness.", performanceTask: "Prepare an open-field nursery observation and readiness note.", evidence: "Seedbed or nursery context, emergence or uniformity observations, hygiene and weather conditions, readiness decision, and review.", criteria: ["Relates conditions to seedling quality.", "Records uniformity and readiness evidence.", "States what requires recheck before transplanting."], remediationFocus: "Practise identifying readiness evidence rather than relying on calendar age alone.", safetyBoundary: "Follow current seed, water, and plant-health requirements through authorised sources." },
  { moduleId: "protective-and-cellular-seedling-production", domainId: "nursery-establishment", title: "Manage protected cellular seedlings", competencyStatement: "Use media, tray, environment, and hardening evidence to judge protected-seedling readiness.", performanceTask: "Complete a protected-seedling quality and hardening check.", evidence: "Batch details, media or tray condition, environment observations, root or plant quality, hardening status, and acceptance decision.", criteria: ["Checks root and canopy quality together.", "Documents hardening evidence.", "Uses accept/hold/referral logic."], remediationFocus: "Repeat the quality pack routine with a complete batch record.", safetyBoundary: "Do not prescribe growing media formulas or inputs without crop, supplier, and local verification." },
  { moduleId: "seedling-production-planning", domainId: "nursery-establishment", title: "Plan seedling supply", competencyStatement: "Match seed, media, method, timing, and plant numbers to a production plan and risk controls.", performanceTask: "Prepare a seedling-production plan that links plant needs, timing, batch traceability, and contingency.", evidence: "Planting target, seed or batch source, method, media or tray assumption, timing, loss contingency, and review point.", criteria: ["Calculates needs transparently.", "Includes a loss or replacement contingency.", "Maintains batch traceability."], remediationFocus: "Rework the plan from final stand target back to nursery requirements.", safetyBoundary: "Verify seed quality, availability, and local requirements using current authorised sources." },
  { moduleId: "field-preparation-mulching-and-trellising", domainId: "nursery-establishment", title: "Prepare a crop-ready field", competencyStatement: "Assess field preparation, cover, and support systems against crop establishment and risk conditions.", performanceTask: "Create a field-readiness checklist for beds, mulch, trellising, water movement, and transplant timing.", evidence: "Field condition, crop stage, preparation observations, support or mulch decision, constraints, and review trigger.", criteria: ["Links preparation to crop and water conditions.", "Identifies operational constraints.", "Sets a readiness check before transplanting."], remediationFocus: "Use a simple crop-ready checklist before planning the next action.", safetyBoundary: "Refer structural, engineering, or high-risk equipment decisions to competent local support." },
  { moduleId: "transplanting", domainId: "nursery-establishment", title: "Establish transplants and review the stand", competencyStatement: "Prepare, execute, and assess transplanting with attention to seedling acceptance and early-stand recovery.", performanceTask: "Record a transplant acceptance and early-stand review.", evidence: "Seedling acceptance, field condition, transplant method, stand count or loss observation, cause uncertainty, and recheck.", criteria: ["Confirms readiness before planting.", "Documents early stand evidence.", "Sets an early-loss investigation trigger."], remediationFocus: "Repeat the transplant execution and early-stand recovery routine.", safetyBoundary: "Do not use unsupported transplant treatments or rates; verify current crop and label requirements." },
  { moduleId: "water-management", domainId: "water-irrigation", title: "Manage root-zone water evidence", competencyStatement: "Assess water-air balance and crop demand to select a low-risk, reviewable water-management next step.", performanceTask: "Complete a root-zone water observation and management record.", evidence: "Crop stage, root-zone observation, delivery or rainfall context, affected zones, decision rationale, and recheck.", criteria: ["Uses root-zone and crop evidence together.", "Compares zones where relevant.", "States a recheck condition."], remediationFocus: "Use the root-zone moisture and air measurement card and water record template.", safetyBoundary: "Do not prescribe irrigation amounts or schedules without local system, weather, soil, and crop evidence." },
  { moduleId: "irrigation-systems", domainId: "water-irrigation", title: "Compare irrigation-system fit", competencyStatement: "Compare irrigation-system performance and suitability using field evidence, crop needs, and operating constraints.", performanceTask: "Prepare an irrigation-system comparison for a stated field and crop context.", evidence: "Water source, system observations, crop stage, field variation, labour or energy constraint, and review measure.", criteria: ["Uses field performance evidence.", "Explains trade-offs.", "Names a measure that can confirm improvement."], remediationFocus: "Revisit the water-quality and delivery observations before comparing systems.", safetyBoundary: "Do not provide design specifications or unverified irrigation prescriptions without competent local assessment." },
  { moduleId: "drip-irrigation-system", domainId: "water-irrigation", title: "Assess drip-delivery performance", competencyStatement: "Measure and review drip delivery, uniformity, and maintenance evidence before changing practice.", performanceTask: "Complete a drip-delivery and uniformity check with a defined follow-up.", evidence: "System layout, delivery observations, comparison points, maintenance context, decision rationale, and recheck.", criteria: ["Uses repeatable comparison points.", "Records delivery variation.", "Sets a maintenance or referral boundary."], remediationFocus: "Use the drip delivery and uniformity measurement card before reattempting the check.", safetyBoundary: "Refer system design, pressure, and water-quality decisions when site evidence or competence is insufficient." },
  { moduleId: "vegetable-fertilisation", domainId: "soil-nutrient-stewardship", title: "Plan vegetable fertilisation from evidence", competencyStatement: "Use crop demand, soil evidence, source and placement considerations, and review indicators to plan vegetable fertilisation.", performanceTask: "Complete a vegetable-fertilisation record with 4R evidence and a response review.", evidence: "Crop stage, soil or crop evidence, source assumptions, placement/timing considerations, safety or label check, and review.", criteria: ["Connects action to field evidence.", "Makes source and timing assumptions visible.", "Defines response monitoring."], remediationFocus: "Complete the fertilisation record and 4R evidence check before reattempting the formal assessment.", safetyBoundary: "Product choice, rate, and legal conditions require current local laboratory, label, and authorised advice." },
  { moduleId: "field-care-and-maintenance", domainId: "crop-care-quality", title: "Maintain crop structure and market potential", competencyStatement: "Prioritise crop-care actions using canopy, crop stage, labour, quality, and follow-up evidence.", performanceTask: "Prepare a crop-care priority note for canopy, support, pollination, or quality maintenance.", evidence: "Crop stage, observed condition, labour or material constraint, priority action, quality indicator, and review date.", criteria: ["Prioritises a time-sensitive need.", "Connects action to market or crop quality.", "Includes a review indicator."], remediationFocus: "Reframe the task around one observable crop-care risk and one practical next action.", safetyBoundary: "Do not make pesticide, growth-regulator, or pollination claims without verified current sources and authority." },
  { moduleId: "harvesting-and-post-harvest-handling", domainId: "crop-care-quality", title: "Protect harvest and post-harvest quality", competencyStatement: "Identify the highest preventable harvest-to-buyer loss risk and implement a reviewable quality-control sequence.", performanceTask: "Complete a harvest handling and quality observation record.", evidence: "Maturity criteria, timing, tool/container condition, hygiene or shade observations, buyer requirement, and outcome measure.", criteria: ["Identifies a preventable loss point.", "Includes traceability or hygiene conditions.", "Measures quality or rejection outcome."], remediationFocus: "Use the harvest capstone evidence pack and record one complete handling sequence.", safetyBoundary: "Verify current food-safety, interval, buyer, and regulatory requirements through authorised sources." },
  { moduleId: "field-diagnosis-in-vegetable-crops", domainId: "crop-health-stewardship", title: "Frame a qualified field diagnosis", competencyStatement: "Separate patterns, symptoms, signs, contributing conditions, and uncertainty before naming a provisional explanation.", performanceTask: "Complete a structured field-diagnosis note with competing explanations and a safe next evidence step.", evidence: "Field pattern, affected/unaffected comparison, symptom or sign description, root/soil/water context, uncertainty, and referral/recheck.", criteria: ["Keeps visible evidence distinct from explanation.", "Names competing explanations.", "States a qualified next step or referral boundary."], remediationFocus: "Use the photo-annotation exercise and diagnosis-to-IPM capstone evidence model.", safetyBoundary: "A field observation or image cannot confirm a disease, cause, or treatment without appropriate verification." },
  { moduleId: "disease-identification-and-management", domainId: "crop-health-stewardship", title: "Interrupt disease risk with evidence", competencyStatement: "Use disease-cycle, field-pattern, crop-history, and uncertainty evidence to prioritise prevention and lawful escalation.", performanceTask: "Prepare a disease-risk decision note that separates prevention, monitoring, and conditions for referral or product consideration.", evidence: "Pattern, symptom/sign evidence, crop history, weather or water context, preventive actions, and escalation boundary.", criteria: ["Links actions to evidence and disease-cycle conditions.", "Prioritises prevention and monitoring.", "States what must be verified before escalation."], remediationFocus: "Revisit competing explanations and prevention steps before considering intervention options.", safetyBoundary: "Do not identify a pathogen or prescribe a product without qualified confirmation and current lawful label verification." },
  { moduleId: "insect-pests-and-mites-identification-and-management", domainId: "crop-health-stewardship", title: "Observe pest and beneficial evidence", competencyStatement: "Record injury, pest stage or count, beneficial organisms, field pattern, and uncertainty as distinct evidence.", performanceTask: "Complete a repeatable pest-and-beneficial observation record for a field zone.", evidence: "Sample unit, injury, pest evidence, beneficial evidence, crop stage, field pattern, and recheck route.", criteria: ["Separates pests, injury, and beneficials.", "Uses a repeatable observation unit.", "Avoids drawing a treatment conclusion from a single observation."], remediationFocus: "Use the quantified scouting protocol and visual annotation exercise before repeating the check.", safetyBoundary: "Do not convert an insect observation into a control decision without current threshold, crop, legal, and label verification." },
  { moduleId: "integrated-pest-management", domainId: "crop-health-stewardship", title: "Make a reviewable IPM decision", competencyStatement: "Use quantified scouting, prevention, beneficial evidence, and recheck logic to select an IPM next step.", performanceTask: "Complete a quantified scouting sheet and IPM decision rationale with a recheck or referral condition.", evidence: "Question, sampling route, counts or incidence, beneficials, pattern, decision rationale, uncertainty, and recheck.", criteria: ["Uses comparable sampling evidence.", "Retains beneficial-organism observations.", "Defines a decision boundary and review condition."], remediationFocus: "Complete the scouting protocol and printable scouting sheet before reattempting the module check.", safetyBoundary: "No universal threshold, treatment, or legal action is implied; verify current local conditions and authorised sources." },
  { moduleId: "responsible-use-of-pesticides", domainId: "crop-health-stewardship", title: "Recognise and escalate pesticide risk safely", competencyStatement: "Recognise unsafe pesticide situations, stop work, protect people and water, document facts, and use authorised channels.", performanceTask: "Complete the pesticide incident drill and a safety-focused evidence record.", evidence: "Observed hazard, stop-work action, area or water protection, label/employer/authorised channel check, factual record, and review.", criteria: ["Stops unsafe work promptly.", "Separates facts from assumptions.", "Uses current label-led and authorised escalation."], remediationFocus: "Repeat the pesticide incident drill and review the explicit non-prescriptive boundaries.", safetyBoundary: "This course does not provide medical treatment, cleanup, disposal, legal-reporting, product, rate, or local emergency instructions." },
  { moduleId: "weed-management", domainId: "crop-health-stewardship", title: "Plan evidence-led weed management", competencyStatement: "Use weed identity features, persistence, crop stage, field pattern, labour, and prevention evidence to prioritise management.", performanceTask: "Create a weed observation and management-sequence note with a safe escalation boundary.", evidence: "Sample area, density or distribution, morphology/persistence clues, crop stage, feasible cultural/physical options, and review measure.", criteria: ["Records weed evidence before action.", "Links persistence to management sequence.", "States a review or lawful escalation condition."], remediationFocus: "Repeat the weed-persistence scenario and field observation sequence.", safetyBoundary: "Verify current local weed-control, equipment, drift, legal, and label requirements before any product action." },
] as const;

export const moduleCompetencyByModuleId = Object.fromEntries(moduleCompetencies.map(competency => [competency.moduleId, competency])) as Record<string, ModuleCompetency>;

export function getDomainModuleCount(domainId: string) {
  return moduleCompetencies.filter(competency => competency.domainId === domainId).length;
}
