export type AppliedFieldBrief = {
  title: string;
  context: string;
  task: string;
  evidence: string;
  standard: string;
};

export const documentModuleFieldBriefs: Record<string, AppliedFieldBrief> = {
  "advisory-practice": { title: "Record a defensible field recommendation", context: "A grower requests advice after uneven crop performance is observed in one part of a field and needs a practical decision that fits the operation.", task: "Clarify the grower’s decision and constraints, compare affected and unaffected areas, separate observation, report, inference, and uncertainty, then agree a bounded next step and review observation.", evidence: "Grower objective, crop stage, mapped field pattern, healthy comparison, roots or soil observations, weather, recent management, stated constraint, permission-aware documentation, and follow-up timing.", standard: "Separate observations, reports, and assumptions; name the decision condition that would require a pause, review, specialist support, or a different recommendation." },
  "soil-and-nutrition": { title: "Build a root-zone evidence sequence", context: "A vegetable field has a poorly drained low area and a better-drained ridge with different crop performance, while a grower asks whether a nutrient input is the answer.", task: "Frame the root-zone question, compare matched areas, record surface-to-profile evidence, keep decision zones separate, design any representative sample, and state the limits of the next nutrient-management decision.", evidence: "Crop stage, zone map, surface condition, root distribution, soil structure and pore observations, moisture condition, recent water or management context, sample plan, laboratory-context assumptions, and review point.", standard: "Preserve the field context from profile to interpretation; do not use one symptom, root observation, or nutrient value to overrule relevant root-zone evidence." },
  "crop-observation": { title: "Build a repeatable scouting record", context: "A crop has uneven vigour and a grower needs a practical next step before a costly intervention.", task: "Scout across field variation, compare healthy and affected plants, record incidence and severity, test competing explanations, and set a verification step.", evidence: "Crop stage, mapped locations, plant and root observations, healthy comparison, incidence, severity, weather, recent practices, and follow-up trigger.", standard: "Present a transparent diagnosis with evidence limits and a next observation; do not turn a field pattern into a certain cause without testing it." },
  "vegetable-production-planning": { title: "Build a field rich picture", context: "A grower is considering a vegetable plot for household use or small commercial sales.", task: "Map climate, soil, slope, water, access, market, biological pressure, and the grower’s purpose before proposing crop or layout.", evidence: "Farm sketch, field history, water and drainage notes, crop purpose, and buyer or household requirements.", standard: "State the evidence behind each planning choice and identify one constraint that needs verification." },
  "cost-planning-and-decisions": { title: "Test a production plan before spending", context: "A planned vegetable block has a crop choice and field dimensions but no costed activity schedule.", task: "Turn the objective and layout into quantities, tasks, timing, costs, plausible return, and a revision decision.", evidence: "Area calculation, plant estimate, input and labour list, local prices, yield assumption, and market-price assumption.", standard: "Use workable units and revise or defer a plan when the assumptions do not support a credible return." },
  "crop-and-variety-selection": { title: "Match a variety to a real field", context: "A buyer requests a preferred product, but local season and elevation may limit performance.", task: "Compare crop family, rotation history, buyer criteria, seasonal fit, supplier information, and farmer experience before selecting seed.", evidence: "Prior crops, elevation or site notes, market specification, seasonal risks, seed-label information, and farmer observations.", standard: "Do not approve a variety until market acceptability and local adaptability are both defensible." },
  "factors-affecting-crop-yield": { title: "Explain yield potential and limits", context: "A high-potential seed option is proposed for a field with uneven soil, moisture, and exposure.", task: "Separate genetic potential from climatic, edaphic, and topographic limits, then identify the limiting factor to manage first.", evidence: "Seed traits, field observations, soil and slope notes, weather pattern, and crop-management capacity.", standard: "Present yield as an interaction between genetics and environment, not as a promise from seed alone." },
  "climatic-factors-affecting-crop-yield": { title: "Make a crop-stage climate plan", context: "A vegetable crop will face changing light, temperature, water, humidity, and wind through its cycle.", task: "Prepare a local crop calendar that links critical stages to likely climate stress and a practical response.", evidence: "Planting window, crop stage, local weather pattern, irrigation capacity, humidity and wind observations.", standard: "Each response must name the climate signal, crop-stage risk, action, and review trigger." },
  "topographic-factors-affecting-crop-yield": { title: "Read slope and water movement", context: "A proposed crop area includes a sloping section, a low point, and different exposure across the farm.", task: "Sketch landform, elevation, runoff paths, erosion risks, and suitable crop or bed placement.", evidence: "Field walk, slope direction, drainage routes, erosion signs, elevation context, and existing structures.", standard: "Translate the sketch into a placement, drainage, or erosion-control decision rather than a description alone." },
  "edaphic-soil-factors-affecting-crop-yield": { title: "Assess the root-zone system", context: "Crop performance differs between two soil areas and a single laboratory value is available.", task: "Combine physical, chemical, and biological observations before identifying the most plausible root-zone limit.", evidence: "Structure, texture, colour, roots, pH or CEC information, organic matter, moisture, and soil-life observations.", standard: "Do not prescribe treatment from one indicator without explaining how the soil lenses agree or differ." },
  "soil-degradation-and-management": { title: "Prioritise a soil-protection response", context: "A field has bare soil, runoff, declining crop response, and wheel traffic after wet weather.", task: "Identify degradation processes, likely drivers, evidence to verify, and linked protection measures.", evidence: "Ground cover, slope, runoff paths, compaction signs, residue practice, nutrient history, and traffic pattern.", standard: "Match each control to a named degradation risk and include a follow-up observation." },
  "nutrients-required-in-plant-nutrition": { title: "Translate a nutrient clue into a question", context: "A crop has a visible leaf symptom and the grower asks for a fertiliser recommendation.", task: "Classify the nutrient role and mobility clue, then define the soil and root-zone evidence needed before choosing a source.", evidence: "Leaf age and pattern, roots, moisture, pH, soil-test information, crop stage, and recent inputs.", standard: "Treat symptoms as clues; do not confuse plant nutrition with automatic fertiliser use." },
  "nutrient-management": { title: "Build a nutrient-flow plan", context: "A productive vegetable field shows repeated nutrient loss and inconsistent crop response.", task: "Map nutrient supply, crop demand, removal, loss pathways, pH, and soil-health practices into an integrated plan.", evidence: "Soil test, crop history, residues, organic sources, fertiliser records, irrigation or runoff pattern, and crop stage.", standard: "The plan must supply, retain, recycle, and protect nutrients rather than only add product." },
  "acid-soil-causes-and-management": { title: "Respond to confirmed soil acidity", context: "A soil test reports low pH after years of acidifying fertiliser use and declining response.", task: "Interpret pH with soil and crop context, then outline liming and complementary management without overliming.", evidence: "Measured pH, soil type, crop condition, fertiliser history, liming-material properties, residues, and organic matter.", standard: "Use measured evidence and state the limitation; a universal lime rate is not acceptable." },
  "how-to-promote-soil-health": { title: "Design a living-soil improvement cycle", context: "A field has low organic matter, weak infiltration, disease pressure, and poor crop-soil fit.", task: "Choose connected practices for cover, organic matter, rotation, disturbance, water, erosion, and crop adaptation.", evidence: "Physical, chemical, biological, and management observations with the farmer’s labour and material capacity.", standard: "Build a practical system of reinforcing practices, not a single isolated input." },
  "collect-soil-samples-for-soil-testing": { title: "Produce a decision-ready soil sample", context: "A farm includes sloping and flat areas with different crop and input histories.", task: "Define homogeneous zones, select sampling points and depth, make a clean composite, and label context for interpretation.", evidence: "Farm map, zone history, tools cleaned between areas, depth record, subsample locations, crop, and management history.", standard: "Keep different decision areas separate and preserve traceability from field to laboratory." },
  "nursery-for-vegetable-production": { title: "Improve a nursery batch", context: "Seedlings are uneven, crowded, and vulnerable to rain, heat, drainage, and insect entry.", task: "Assess roots, spacing, soil, drainage, light, protection, and barrier integrity before deciding readiness or improvement.", evidence: "Root and shoot quality, plant spacing, bed condition, water movement, cover condition, and insect-net gaps.", standard: "A seedling is ready only when root and shoot quality agree with the planned field conditions." },
  "open-field-seedling-production": { title: "Plan a bare-root nursery cycle", context: "A grower needs vigorous bare-root seedlings from an open-field nursery.", task: "Select and prepare a high, drained site; plan thin sowing, climate-responsive covers, hardening, and low-stress transplanting.", evidence: "Site elevation, drainage, weed pressure, bed preparation, sowing density, seedling condition, and weather window.", standard: "Protect roots and spacing from sowing through field establishment; do not transfer nursery stress to the crop." },
  "protective-and-cellular-seedling-production": { title: "Verify cellular transplant readiness", context: "Cell-grown seedlings have variable media moisture and are scheduled to move from protection into field heat.", task: "Check container, media, germination protection, water, nutrition, pest risk, hardening, and root-shoot quality.", evidence: "Cell size, medium condition, tray uniformity, roots, true leaves, moisture record, hardening steps, and forecast.", standard: "Field readiness requires healthy, hardened seedlings—not simply a calendar date." },
  "seedling-production-planning": { title: "Plan seedling supply from field layout", context: "A nursery plan is needed before seed or media is purchased.", task: "Verify seed quality and treatment, calculate needs with replacement capacity, and select media, method, nutrition, and protection.", evidence: "Seed label and storage, bed geometry, plant spacing, replacement allowance, media properties, and production constraints.", standard: "Every seed and media quantity must be traceable to field geometry and establishment capacity." },
  "field-preparation-mulching-and-trellising": { title: "Prepare the production system before planting", context: "A vegetable field is uneven, weedy, poorly drained, and awaiting mulch and trellis materials.", task: "Appraise, clear, lay out, prepare beds and drainage, choose mulch, and schedule support installation for the crop.", evidence: "Field map, soil condition, water movement, bed orientation, mulch type and handling plan, crop family, and trellis timing.", standard: "Complete the soil, water, mulch, and support system before crop establishment." },
  "transplanting": { title: "Establish a uniform transplant stand", context: "Tray seedlings are due for planting in hot conditions with incomplete holes, mulch, and trellis.", task: "Verify field and seedling readiness, moisture, hardening, timing, planting depth, nutrient separation, and early recovery checks.", evidence: "Seedling stage, root condition, soil moisture, weather window, hole and fertiliser placement, and stand count.", standard: "Record the conditions that would delay transplanting and inspect early losses for rapid correction." },
  "water-management": { title: "Protect root-zone water and air", context: "A crop alternates between dry stress before flowering and saturation after heavy irrigation or rain.", task: "Diagnose water-air balance and plan irrigation, conservation, drainage, and water-quality safeguards by soil and crop stage.", evidence: "Soil moisture at rooting depth, texture, crop stage, irrigation duration, rainfall, drainage condition, and source quality.", standard: "Irrigate the functioning root zone; avoid both calendar watering and unsafe water sources." },
  "irrigation-systems": { title: "Choose a system the farm can sustain", context: "A hot, dry vegetable field has limited labour, uneven ground, and a constrained water source.", task: "Compare hand, sprinkler, surface, and drip options against crop demand, soil, slope, water, labour, cost, and maintenance capacity.", evidence: "Critical crop stages, field size, topography, supply quantity and quality, filtration needs, labour, cost, and skills.", standard: "Recommend the system that can be supplied, maintained, and operated as well as agronomically justified." },
  "drip-irrigation-system": { title: "Restore uniform drip delivery", context: "Near-tank plants are wet while far rows are dry and the source water contains sediment.", task: "Check design, filtration, pressure, zones, far-end flow, wetting pattern, clogs, leaks, flushing, and maintenance records.", evidence: "Source quality, filter state, pressure readings, far-end flow, emitter output, soil wetting, leaks, and cleaning history.", standard: "Investigate the full water path before changing the irrigation schedule or replacing parts." },
  "vegetable-fertilisation": { title: "Build a field-specific 4R plan", context: "A grower applies one fertiliser at one rate across fields with different soil tests and crop stages.", task: "Identify limiting factors, interpret crop demand and source analysis, then set source, rate, timing, and placement.", evidence: "Soil NPK and pH, crop stage, prior removals, residue or organic sources, label analysis, roots, and placement conditions.", standard: "Correct the limiting factor and state how the plan will be reviewed after application." },
  "field-care-and-maintenance": { title: "Protect structure, fruit set, and quality", context: "A cucurbit block has ground-crawling vines, canopy crowding, poor set, and fruit contacting soil.", task: "Plan timely support, hygienic pruning, training, pollination diagnosis, and fruit support with crop-stage evidence.", evidence: "Crop family and stage, canopy pattern, support condition, flower and fruit observations, water and nutrition context, and disease signs.", standard: "Use structural crop care to prevent problems; do not treat pruning or trellising as isolated tasks." },
  "harvesting-and-post-harvest-handling": { title: "Run a market-quality protection chain", context: "Produce is harvested at mixed maturity in rough containers and stands in sun before washing.", task: "Set maturity and timing, improve harvest handling, shade, cleaning or cooling, sorting, grading, and food-safety controls.", evidence: "Crop maturity criteria, harvest time, tools and containers, shade, water quality, sanitation, pesticide interval, and defect record.", standard: "Protect quality at every hand-off from field to market; do not rely on downstream sorting to repair damage." },
  "field-diagnosis-in-vegetable-crops": { title: "Write a qualified field diagnosis", context: "A vegetable crop has patchy yellowing and stunting after a new irrigation pattern and recent input change.", task: "Inspect symptoms, signs, roots, pattern, history, soil, water, climate, and inputs; compare biotic and abiotic explanations.", evidence: "Affected and unaffected plants, incidence and severity, field map, root condition, recent practices, weather, and input records.", standard: "State the evidence, uncertainty, safe next step, and condition that would trigger escalation." },
  "disease-identification-and-management": { title: "Break a disease-conducive cycle", context: "Wet weather coincides with spreading wilt and leaf spots, and the grower requests an immediate product choice.", task: "Qualify the diagnosis, rule out look-alikes, identify likely disease category and spread pathway, and build prevention-led IPM.", evidence: "Symptoms and signs, plant part, pattern, incidence, roots, wetness, crop history, material source, sanitation, and vector evidence.", standard: "Verify the cause and break spread pathways before any lawful, label-directed product decision." },
  "insect-pests-and-mites-identification-and-management": { title: "Protect crops and beneficials from verified pests", context: "Tomato has whiteflies, virus-like symptoms, border weeds, and traps that also catch beneficial insects.", task: "Identify damaging stage and injury, assess vector risk, then plan sanitation, exclusion, target-aware trapping, natural-enemy protection, and IPM.", evidence: "Pest stage and density, injury pattern, crop part, infected plants, host weeds, trap catch, beneficial organisms, and field conditions.", standard: "Do not let a product or a trap replace diagnosis, source removal, or beneficial-insect safeguards." },
  "integrated-pest-management": { title: "Make an IPM decision from field evidence", context: "A brassica field has caterpillar injury, weeds, crowding, and a history of broad-spectrum spraying.", task: "Scout and quantify the problem, reduce conducive conditions, select targeted physical or biological options, and define constrained escalation and review.", evidence: "Plant and pest records, field pattern, crop condition, natural enemies, prior actions, target threshold or decision rationale, and follow-up date.", standard: "Use prevention, monitoring, intervention, and review as an evidence-led process—not a pesticide package." },
  "responsible-use-of-pesticides": { title: "Stop an unsafe spray decision", context: "A grower plans to use an unlabeled leftover product in heat and wind with a leaking, uncalibrated sprayer near water.", task: "Verify the problem and alternatives, then identify the label, legal crop-target fit, safety requirements, equipment fixes, weather window, and records needed.", evidence: "Product label and expiry, crop and target, registration, PHI, PPE, water-source location, sprayer inspection, calibration, weather, and application record.", standard: "Do not proceed unless product, target, law, label, people, water, equipment, and weather requirements all agree." },
  "weed-management": { title: "Break a weed competition and persistence cycle", context: "A direct-seeded tomato field has early weed patches, flowering purslane, triangular-stem weeds, and persistent nutsedge.", task: "Map density and crop stage, classify weeds, identify seed or tuber persistence, then combine timely physical, cultural, biological, and justified chemical controls.", evidence: "1 m² sample, field map, weed morphology, flowering or tuber evidence, crop stage, alternative-host observations, equipment, weather, and label checks.", standard: "Control the persistence mechanism and critical interference risk, not only visible top growth." },
};
