import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Copy, Link2, RefreshCw, ShieldOff } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function RecordReviewSharing({ recordId }: { recordId: number }) {
  const [reviewerName, setReviewerName] = useState("");
  const sharesQuery = trpc.reviewShares.list.useQuery({ recordId });
  const utils = trpc.useUtils();
  const createShare = trpc.reviewShares.create.useMutation({ onSuccess: async () => { await utils.reviewShares.list.invalidate({ recordId }); setReviewerName(""); toast.success("Review link created", { description: "The learner controls when the link remains active." }); }, onError: error => toast.error("Unable to create review link", { description: error.message }) });
  const revokeShare = trpc.reviewShares.revoke.useMutation({ onSuccess: () => utils.reviewShares.list.invalidate({ recordId }), onError: error => toast.error("Unable to revoke review link", { description: error.message }) });
  const copyLink = async (token: string) => { const link = `${window.location.origin}/review/${token}`; try { await navigator.clipboard.writeText(link); toast.success("Review link copied"); } catch { window.prompt("Copy this review link", link); } };
  return <section className="rounded-[22px] border border-[#dbe7d7] bg-[#f7fbf4] p-5"><div className="flex items-start gap-3"><Link2 className="mt-0.5 h-4 w-4 shrink-0 text-[#4c7e57]" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#658164]">Learner-controlled review</p><p className="mt-2 text-sm font-semibold leading-6 text-[#314b39]">Share this record when you choose.</p></div></div><p className="mt-3 text-xs leading-5 text-[#607460]">Create a private review link for a supervisor or peer. You can revoke it at any time.</p><div className="mt-4"><Label htmlFor="reviewer-name">Reviewer name (optional)</Label><Input id="reviewer-name" value={reviewerName} onChange={event => setReviewerName(event.target.value)} maxLength={160} className="mt-2 bg-white" placeholder="e.g., Extension supervisor" /><Button disabled={createShare.isPending} onClick={() => createShare.mutate({ recordId, reviewerName: reviewerName || undefined })} className="mt-3 w-full rounded-full bg-[#315f47] text-xs font-bold hover:bg-[#214d36]"><Link2 className="mr-1.5 h-3.5 w-3.5" />{createShare.isPending ? "Creating link" : "Create review link"}</Button></div><div className="mt-5 space-y-3">{sharesQuery.isLoading ? <p className="text-xs text-[#718071]">Loading review links…</p> : sharesQuery.isError ? <Button variant="ghost" onClick={() => sharesQuery.refetch()} className="h-auto p-0 text-xs font-bold text-[#8a593d] hover:bg-transparent"> <RefreshCw className="mr-1.5 h-3.5 w-3.5" />Retry loading review links</Button> : sharesQuery.data?.length ? sharesQuery.data.map(share => <div key={share.id} className="rounded-xl border border-[#dfe9dc] bg-white/75 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold text-[#3e5a42]">{share.reviewerName || "Unnamed reviewer"}</p><p className="mt-1 text-[10px] text-[#748474]">{share.revokedAt ? "Revoked" : share.reviewedAt ? "Review received" : "Active link"}</p></div>{!share.revokedAt && <Button variant="ghost" size="sm" onClick={() => revokeShare.mutate({ id: share.id })} className="h-7 px-2 text-[10px] font-bold text-[#914f36] hover:bg-[#fff5ef] hover:text-[#7d3f2b]"><ShieldOff className="mr-1 h-3 w-3" />Revoke</Button>}</div>{share.reviewComment && <p className="mt-3 border-t border-[#e4ebe1] pt-3 text-xs leading-5 text-[#536653]">{share.reviewComment}</p>}{!share.revokedAt && <Button variant="outline" size="sm" onClick={() => copyLink(share.shareToken)} className="mt-3 h-8 rounded-full text-[10px] font-bold"><Copy className="mr-1 h-3 w-3" />Copy link</Button>}</div>) : <p className="text-xs leading-5 text-[#718071]">No review links have been created for this record.</p>}</div></section>;
}
